Universe           = vanilla
Executable         = run_truth_ratio_pos.sh
getenv          = True
Output          = /sphenix/user/mjpeters/analysis/LightFlavorRatios/truth_ratio/logs/truth_ratio_pos_$(Process).out
Error           = /sphenix/user/mjpeters/analysis/LightFlavorRatios/truth_ratio/logs/truth_ratio_pos_$(Process).err
Log             = /sphenix/user/mjpeters/analysis/LightFlavorRatios/truth_ratio/logs/truth_ratio_pos_$(Process).log
Initialdir      = .
PeriodicHold    = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 2GB
Priority           = 20
job_lease_duration = 3600
Arguments          = $(Process)
Queue 10000
