Universe 	= vanilla
Executable 	= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterTowerENC/macros/CompareParticlesToTowers.sh
Arguments       = DST_TRUTH_JET_pythia8_Jet30_3MHz-0000000011-00000.root DST_CALO_CLUSTER_pythia8_Jet30_3MHz-0000000011-00000.root DST_TRUTH_RECO_pythia8_Jet30_3MHz-0000000011-00000.root DST_GLOBAL_pythia8_Jet30_3MHz-0000000011-00000.root 100  
Output  	= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterTowerENC/macros/condor_0.out
Error 		=/gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterTowerENC/macros/condor_0.err
Log  		=/gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterTowerENC/macros/condor_0.log
Initialdir  	= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/CalorimeterTowerENC
PeriodicHold 	= (NumJobStarts>=1 && JobStatus == 1)
accounting_group = group_phenix.u
accounting_group_user = sgross
request_memory = 32192MB
Priority = 90
job_lease_duration = 3600
Queue 1
