#+title: EMCal Bias Study

* List of all databases
#+begin_src bash
psql -h sphnxdbmaster.sdcc.bnl.gov --list
#+end_src

* Extract EMCal Bias from Database
#+begin_src bash
psql -h sphnxdbmaster.sdcc.bnl.gov emcal -c "select *,cast(1000*(bias-66.5-2.5) as int) as gs from vop order by sector,ib,channel asc;" --csv > files/emcal-bias.csv
#+end_src

* EMCal Master Spreadsheet
https://docs.google.com/spreadsheets/d/1r8V_NYTaj0hXuvuMlxOB-5J2lB38dfHXbgemcb7WXKM/edit?usp=drive_link

* Read Bias macro
#+begin_src bash
make && ./bin/read-Bias files/emcal-bias.csv files/serial-to-sector.csv files/IB-channel-to-ADC-channel.csv files/EMCal-block-info.csv calibration/emcal_2024_prelim_calibration.root plots/EMCal-Info/plots.pdf files/vop.csv output/EMCal-block-info.root
#+end_src

* Write Bias macro
#+begin_src bash
make && ./bin/write-Bias files/emcal-bias.csv files/serial-to-sector.csv files/IB-channel-to-ADC-channel.csv scratch/bias-test 41 2000 100 1
#+end_src

** Write bias v2
Allows for reading a root file and 2D histogram and generate the bias offset configuration files.
#+begin_src bash
make && ./bin/write-Biasv2 <path/to/rootfile> <histName> files/serial-to-sector.csv files/IB-channel-to-ADC-channel.csv scratch/bias-test
#+end_src

Example:
#+begin_src bash
make && ./bin/write-Biasv2 output/EMCal-block-info.root h2Offset files/serial-to-sector.csv files/IB-channel-to-ADC-channel.csv scratch/bias-test
#+end_src

* Update Bias macro
#+begin_src bash
make && ./bin/update-Bias output/EMCal-block-info.root plots/bias-update-plots/plots.pdf
#+end_src
Alternatively
#+begin_src bash
root -b -l -q 'macros/update-Bias.C("output/EMCal-block-info.root","plots/bias-update/plots.pdf")'
#+end_src

* Update Offset macro
#+begin_src bash
make && ./bin/update-Offset output/EMCal-block-info.root plots/offset-update-plots/plots.pdf
#+end_src
Alternatively
#+begin_src bash
root -b -l -q 'macros/update-Offset.C("output/EMCal-block-info.root","plots/offset-update/plots.pdf")'
#+end_src

* Event Combiner
Combine a list of prdfs into one:
#+begin_src bash
xargs eventcombiner -vpfi calib-000[run]-0000.prdf < [prdf-list]
#+end_src

* Fun4All Quick Tests

** After editing Makefile.am
#+begin_src bash
rm -rf build && mkdir build && cd build && ../src/autogen.sh --prefix=$MYINSTALL && cd .. && make install -j8 --directory build && rm -f bin/Fun4All_Year2_Fitting && make && ./bin/Fun4All_Year2_Fitting data/calib-00059097-0000.prdf test.root 20 2>/dev/null
#+end_src

** After editing .cc or .h
#+begin_src bash
make install -j8 --directory build && rm -f bin/Fun4All_Year2_Fitting && make && ./bin/Fun4All_Year2_Fitting data/calib-00059097-0000.prdf test.root 20 2>/dev/null
#+end_src

*** With Pulser data
#+begin_src bash
make install -j8 --directory build && rm -f bin/Fun4All_Year2_Fitting && make && ./bin/Fun4All_Year2_Fitting pulser/data-00058514-0000.prdf test.root 20 1 2>/dev/null
#+end_src

* Display
Generate plots from the output of the Waveform Fitting results
#+begin_src bash
make && ./bin/display scratch/calo/test.list files/runs-gain-map-offsets.csv plots/ADC/plots.pdf
#+end_src
Alternatively:
#+begin_src bash
root -b -l -q 'macros/display.C("calo/test.list","files/runs-gain-map-offsets.csv","plots/ADC/plots.pdf")'
#+end_src

** Pulser Runs
Generate plots from the output of the Waveform Fitting results
#+begin_src bash
make && ./bin/displayv2 scratch/pulser/test.list plots/ADC-pulser/plots.pdf
#+end_src
Alternatively:
#+begin_src bash
root -b -l -q 'macros/displayv2.C("calo/test-pulser.list","plots/ADC-pulser/plots.pdf")'
#+end_src

* Condor
** Resubmit Failed Jobs
#+begin_src bas
rg -vFf <(ls output | cut -d "-" -f2 | awk '{x=$0+0;print x}') jobs.list > resubmit.list
#+end_src

* Data taking instructions for EMCal via LEDs

** Configure EMCal for data taking
1) Turn EMCal ON (bias and lv).
2) Turn EMCal Controller Crates ON via vision client GUI.
3) Run from daq02 to setup the EMCal:
#+begin_src bash
/home/phnxrc/haggerty/emcal/offandon/emcalon
#+end_src

** Setup DAQ
1) From an SEB machine run:
#+begin_src bash
bash ~/samfred/quickscripts/rc_setup_local.sh 5 seb{00..15} && \
echo "rc_setup_local done" && sleep 2 && \
ssh opc0 "python3 ~/haggerty/emcal/calcon/ledtest.py 32" && \
echo "LEDs configured" && sleep 2 && \
gl1_gtm_client gtm_set_mode 5 0 && \
echo "gtm_client set" && sleep 2 && \
gl1_gtm_client gtm_load_modebits 5 /home/phnxrc/operations/gl1_gtm/EMCAL_pulse_100Hz.scheduler && \
echo "gtm_load_modbits set" && sleep 2 && \
RunControl.py &
#+end_src

2) After DAQ work is completed, close Run Control gui and from an SEB machine run:
#+begin_src bash
rc_shutdown
#+end_src

** Load the desired bias offsets
Run from daq02:
#+begin_src bash
ln -sfn <path/to/offsets> /home/phnxrc/haggerty/emcal/config && echo "link set" && \
~/haggerty/emcal/calcon/biasallsectorsfast.py && echo "offsets loaded" && \
~/haggerty/emcal/calcon/emcalsector.py bias --sector 48 && echo "verified"
#+end_src

After this take run via the Run Control GUI (begin and end).

** Clean Up
At the end of datataking ensure the original offsets are loaded:
#+begin_src bash
ln -sfn /home/phnxrc/haggerty/emcal/vop-1008 /home/phnxrc/haggerty/emcal/config && echo "link set" \
~/haggerty/emcal/calcon/biasallsectorsfast.py && echo "offsets loaded"
#+end_src

** View Runs Transfer Status
1) From local computer run:
#+begin_src bash
ssh anarde@cssh.rhic.bnl.gov -L 3128:batch3.phy.bnl.gov:3128
#+end_src
Note: replace anarde with your username.

2) Configure the FoxyProxy

3) Nagivate to http://www.sphenix-intra.bnl.gov:7815/cgi-bin/
