void GammaNeutronEnergy2DGraphMaker()
{
  TFile *fin = TFile::Open("Gamma_Neutron_Energy_Graphs.root");
  gROOT->cd();
  TCanvas *c1 = new TCanvas();
  gStyle->SetOptStat(0);
  TH2F *n2h2 = new TH2F("Percentage of Energy Deposited by 2 GeV Particles vs Cone Size","Percentage of Energy Deposited by 2 GeV Particles vs Cone Size",1,0,1,1,0,1.1);
  TGraph *n2gr = (TGraph *) fin->Get("neutron2GeV")->Clone();
  n2h2->SetXTitle("Cone Size");
  n2h2->SetYTitle("Percentage of Energy Deposited");
  n2h2->Draw();
  n2gr->Draw("*");
  TGraph *g2gr = (TGraph *) fin->Get("gamma2GeV")->Clone();
  //TH2F *g2h2 = new TH2F("g2h2","g2h2",1,0,1,1,0,1.1);
  //  g2h2->Draw("same");
  g2gr->Draw("*");
  TLine *tl = new TLine();
  tl->SetLineStyle(2);
  tl->DrawLine(0.1,0,0.1,1.1);
 TLine *t2 = new TLine();
  t2->SetLineStyle(6);
  t2->DrawLine(0.024,0,0.024,1.1);
  TLegend *legrda = new TLegend(0.63,0.24,0.84,0.59,NULL,"brNDC");
  legrda->SetLineColor(1);
  legrda->SetLineStyle(1);
  legrda->SetLineWidth(1);
  legrda->SetFillColor(10);
  legrda->SetFillStyle(1001);
  legrda->SetBorderSize(0);
  //  legrda->SetTextSize(labelsize);
  //legrda->AddEntry(hjbkg,"HIJING bkg"); 
  legrda->AddEntry(gamma2GeV,          "2 GeV Gamma","p"); 
  legrda->AddEntry(neutron2GeV,          "2 GeV Neutron", "p"); 
  legrda->AddEntry(tl,          "HCAL tower size","l"); 
  legrda->AddEntry(t2,"EMCAL tower size","l");
  legrda->Draw();
  c1->Print("Gamma_vs_Neutron_2GeV.png");
  
  TCanvas *c2 = new TCanvas();
  gStyle->SetOptStat(0);
  TH2F *n50h2 = new TH2F("Percentage of Energy Deposited by 50 GeV Particles vs Cone Size","Percentage of Energy Deposited by 50 GeV Particles vs Cone Size",1,0,1,1,0,1.1);
  TGraph *n50gr = (TGraph *) fin->Get("neutron50GeV")->Clone();
  n50h2->SetXTitle("Cone Size");
  n50h2->SetYTitle("Percentage of Energy Deposited");
  n50h2->Draw();
  n50gr->Draw("*");
  TGraph *g50gr = (TGraph *) fin->Get("gamma50GeV")->Clone();
  //TH2F *g50h2 = new TH2F("g50h2","g50h2",1,0,1,1,0,1.1);
  //g50h2->Draw("same");
  g50gr->Draw("*");
  TLine *tl = new TLine();
  tl->SetLineStyle(2);
  tl->DrawLine(0.1,0,0.1,1.1);
 TLine *t2 = new TLine();
  t2->SetLineStyle(6);
  t2->DrawLine(0.024,0,0.024,1.1);
  TLegend *legrda2 = new TLegend(0.63,0.24,0.84,0.59,NULL,"brNDC");
  legrda2->SetLineColor(1);
  legrda2->SetLineStyle(1);
  legrda2->SetLineWidth(1);
  legrda2->SetFillColor(10);
  legrda2->SetFillStyle(1001);
  legrda2->SetBorderSize(0);
  //  legrda2->SetTextSize(labelsize);
  //legrda2->AddEntry(hjbkg,"HIJING bkg"); 
  legrda2->AddEntry(gamma50GeV,          "50 GeV Gamma","p"); 
  legrda2->AddEntry(neutron50GeV,          "50 GeV Neutron", "p"); 
  legrda2->AddEntry(tl,          "HCAL tower size","l");
  legrda2->AddEntry(t2,"EMCAL tower size","l"); 
  legrda2->Draw();
  c2->Print("Gamma_vs_Neutron_50GeV.png");
  

  TCanvas *c3 = new TCanvas();
  gStyle->SetOptStat(0);
  TH2F *ga2 = new TH2F("Gamma Energy Deposition vs Cone Size","Gamma Energy Deposition vs Cone Size",1,0,0.5,1,0,1.1);
  TGraph *gamma2GeV = (TGraph *) fin->Get("gamma2GeV")->Clone();
  ga2->SetXTitle("Cone Size");
  ga2->SetYTitle("Percentage of Energy Deposited");
  ga2->Draw();
  gamma2GeV->SetMarkerSize(1);
  gamma2GeV->SetMarkerStyle(4);
  gamma2GeV->Draw("P");
  int pz[7] = {4,8,12,16,32,40,50};
  int col[7] = {2,9,4,5,6,7,8};
  int mark[7] = {24,25,26,27,28,35,36};
  for (int i=0; i<7;i++)
    {
      char hname[100];
      sprintf(hname,"gamma%dGeV",pz[i]);
      //TH2F *gall = new TH2F(hname,hname,1,0,0.5,1,0,1.1);
      TGraph *gamall = (TGraph *) fin->Get(hname);
      //gall->Draw("same");
      gamall->SetMarkerColor(col[i]);
      gamall->SetMarkerStyle(4);
      gamall->SetMarkerSize(1);
      //gamall->SetLineWidth(3);
      gamall->Draw("P");
    }
  TLine *tl = new TLine();
  tl->SetLineStyle(2);
  tl->DrawLine(0.1,0,0.1,1.1);
  TLine *t2 = new TLine();
  t2->SetLineStyle(6);
  t2->DrawLine(0.024,0,0.024,1.1);
  TLegend *legrda3 = new TLegend(0.63,0.24,0.84,0.59,NULL,"brNDC");
  legrda3->SetLineColor(1);
  legrda3->SetLineStyle(1);
  legrda3->SetLineWidth(1);
  legrda3->SetFillColor(10);
  legrda3->SetFillStyle(1001);
  legrda3->SetBorderSize(0);
  //  legrda3->SetTextSize(labelsize);
  //legrda3->AddEntry(hjbkg,"HIJING bkg");
  legrda3->AddEntry(gamma2GeV,          "2 GeV Gamma","p");
    legrda3->AddEntry(gamma4GeV,          "4 GeV Gamma","p");
    legrda3->AddEntry(gamma8GeV,          "8 GeV Gamma","p");
    legrda3->AddEntry(gamma12GeV,          "12 GeV Gamma","p");
    legrda3->AddEntry(gamma16GeV,          "16 GeV Gamma","p");
    legrda3->AddEntry(gamma32GeV,          "32 GeV Gamma","p");
    legrda3->AddEntry(gamma40GeV,          "40 GeV Gamma","p");
    legrda3->AddEntry(gamma50GeV,          "50 GeV Gamma","p");
   legrda3->AddEntry(tl,          "HCAL tower size","l" );
   legrda3->AddEntry(t2,"EMCAL tower size", "l");
  legrda3->Draw();
  c3->Print("Gamma_All.png");
  
  TCanvas *c4 = new TCanvas();
  gStyle->SetOptStat(0);
  TH2F *an2 = new TH2F("Antineutron Energy Deposition vs Cone Size","Antineutron Energy Deposition vs Cone Size",1,0,0.5,1,0,1.1);
  TGraph *anti_neutron2GeV = (TGraph *) fin->Get("anti_neutron2GeV")->Clone();
  an2->SetXTitle("Cone Size");
  an2->SetYTitle("Percentage of Energy Deposited");
  an2->Draw();
  anti_neutron2GeV->SetMarkerSize(1);
  anti_neutron2GeV->SetMarkerStyle(4);
  anti_neutron2GeV->Draw("P");
  int pz[7] = {4,8,12,16,32,40,50};
  int col[7] = {2,9,4,5,6,7,8};
  int mark[7] = {24,25,26,27,28,35,36};
  for (int i=0; i<7;i++)
    {
      char hname[100];
      sprintf(hname,"anti_neutron%dGeV",pz[i]);
      //TH2F *gall = new TH2F(hname,hname,1,0,0.5,1,0,1.1);
      TGraph *anall = (TGraph *) fin->Get(hname);
      //gall->Draw("same");
      anall->SetMarkerColor(col[i]);
      anall->SetMarkerStyle(4);
      anall->SetMarkerSize(1);
      //gamall->SetLineWidth(3);
      anall->Draw("P");
    }
  TLine *tl = new TLine();
  tl->SetLineStyle(2);
  tl->DrawLine(0.1,0,0.1,1.1);
  TLine *t2 = new TLine();
  t2->SetLineStyle(6);
  t2->DrawLine(0.024,0,0.024,1.1);
  TLegend *legrda4 = new TLegend(0.63,0.24,0.84,0.59,NULL,"brNDC");
  legrda4->SetLineColor(1);
  legrda4->SetLineStyle(1);
  legrda4->SetLineWidth(1);
  legrda4->SetFillColor(10);
  legrda4->SetFillStyle(1001);
  legrda4->SetBorderSize(0);
  //  legrda4->SetTextSize(labelsize);
  //legrda4->AddEntry(hjbkg,"HIJING bkg");
legrda4->AddEntry(anti_neutron2GeV,          "2 GeV Anti Neutron","p");
legrda4->AddEntry(anti_neutron4GeV,          "4 GeV Anti Neutron","p");
legrda4->AddEntry(anti_neutron8GeV,          "8 GeV Anti Neutron","p");
legrda4->AddEntry(anti_neutron12GeV,          "12 GeV Anti Neutron","p");
legrda4->AddEntry(anti_neutron16GeV,          "16 GeV Anti Neutron","p");
legrda4->AddEntry(anti_neutron32GeV,          "32 GeV Anti Neutron","p");
legrda4->AddEntry(anti_neutron40GeV,          "40 GeV Anti Neutron","p");
legrda4->AddEntry(anti_neutron50GeV,          "50 GeV Anti Neutron","p");
   legrda4->AddEntry(tl,          "HCAL tower size","l"); 
   legrda4->AddEntry(t2,"EMCAL Tower size","l");
  legrda4->Draw();
  c4->Print("Antineutron_All.png");

  TCanvas *c5 = new TCanvas();
  gStyle->SetOptStat(0);
  TH2F *n2 = new TH2F("Neutron Energy Deposition vs Cone Size","Neutron Energy Deposition vs Cone Size",1,0,0.5,1,0,1.1);
  TGraph *neutron2GeV = (TGraph *) fin->Get("neutron2GeV")->Clone();
  n2->SetXTitle("Cone Size");
  n2->SetYTitle("Percentage of Energy Deposited");
  n2->Draw();
  neutron2GeV->SetMarkerSize(1);
  neutron2GeV->SetMarkerStyle(4);
  neutron2GeV->Draw("P");
  int pz[7] = {4,8,12,16,32,40,50};
  int col[7] = {2,9,4,5,6,7,8};
  int mark[7] = {24,25,26,27,28,35,36};
  for (int i=0; i<7;i++)
    {
      char hname[100];
      sprintf(hname,"neutron%dGeV",pz[i]);
      //TH2F *gall = new TH2F(hname,hname,1,0,0.5,1,0,1.1);
      TGraph *nall = (TGraph *) fin->Get(hname);
      //gall->Draw("same");
      nall->SetMarkerColor(col[i]);
      nall->SetMarkerStyle(4);
      nall->SetMarkerSize(1);
      //gamall->SetLineWidth(3);
      nall->Draw("P");
    }
 TLine *tl = new TLine();
  tl->SetLineStyle(2);
  tl->DrawLine(0.1,0,0.1,1.1);
 TLine *t2 = new TLine();
  t2->SetLineStyle(6);
  t2->DrawLine(0.024,0,0.024,1.1);
  TLegend *legrda5 = new TLegend(0.63,0.24,0.84,0.59,NULL,"brNDC");
  legrda5->SetLineColor(1);
  legrda5->SetLineStyle(1);
  legrda5->SetLineWidth(1);
  legrda5->SetFillColor(10);
  legrda5->SetFillStyle(1001);
  legrda5->SetBorderSize(0);
  //  legrda->SetTextSize(labelsize);
  //legrda->AddEntry(hjbkg,"HIJING bkg");
legrda5->AddEntry(neutron2GeV,          "2 GeV Neutron","p");
legrda5->AddEntry(neutron4GeV,          "4 GeV Neutron","p");
legrda5->AddEntry(neutron8GeV,          "8 GeV Neutron","p");
legrda5->AddEntry(neutron12GeV,          "12 GeV Neutron","p");
legrda5->AddEntry(neutron16GeV,          "16 GeV Neutron","p");
legrda5->AddEntry(neutron32GeV,          "32 GeV Neutron","p");
legrda5->AddEntry(neutron40GeV,          "40 GeV Neutron","p");
legrda5->AddEntry(neutron50GeV,          "50 GeV Neutron","p");
   legrda5->AddEntry(tl,          "HCAL tower size","l"); 
   legrda5->AddEntry(t2,"EMCAL tower size","l");
  legrda5->Draw();
  c5->Print("Neutron_All.png");

  fin->Close();
}
  
