Universe           = vanilla
Initialdir         = /sphenix/user/ChengWei/INTT/INTT_dNdeta_repo/DST_MC/control_files/data_20869_F4A/2024_05_07/evt_tracklet/condor_outputs
Executable         = /sphenix/user/ChengWei/INTT/INTT_dNdeta_repo/DST_MC/control_files/data_20869_F4A/2024_05_07/evt_tracklet/run_root_sub_the_file_number.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 4GB
Priority           = 20
job_lease_duration = 172800
nEvents            = NEVENTS
InputfilelistIdx   = INPUTFILELISTIDX
FileName           = FILENAME
skipEvt            = 0
Output             = /sphenix/user/ChengWei/INTT/INTT_commissioning/ZeroField/F4A_20869/2024_05_07/folder_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/evt_tracklet/CW_log/condor_the_file_number.out
Error              = /sphenix/user/ChengWei/INTT/INTT_commissioning/ZeroField/F4A_20869/2024_05_07/folder_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/evt_tracklet/CW_log/condor_the_file_number.err
Log                = /sphenix/user/ChengWei/INTT/INTT_commissioning/ZeroField/F4A_20869/2024_05_07/folder_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/evt_tracklet/CW_log/condor_the_file_number.log
Arguments          = "$(nEvents) $(InputfilelistIdx) $(FileName) $(skipEvt)"
Queue 1

