// Class: ReadMLPnew
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPnew
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/02       [398850]
Creator        : cdean
Date           : Tue Apr 20 16:39:06 2021
Host           : Linux cvmfswrite02.sdcc.bnl.gov 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 15:23:27 CDT 2019 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /gpfs/mnt/gpfs02/sphenix/user/cdean/scripts/HF_trigger_ML/TMVA/Odd/wCalo
Training events: 31922
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
max(track_1_IP,track_2_IP)    maxTrackDCA_3D                maxTrackDCA_3D                track-vertex 3D DCA, max      units                             'F'    [0.00383873376995,4.99581956863]
max(abs(track_1_IP_xy),abs(track_2_IP_xy)) maxTrackDCA_2D                             maxTrackDCA_2D                             track-vertex 2D DCA, max                   units                                          'F'    [9.33057162911e-05,4.8996257782]
track_1_track_2_DCA           track_1_track_2_DCA           track_1_track_2_DCA           track-track 3D DCA            units                             'F'    [1.57269468559e-07,0.0499997623265]
INTT_meanHits                 INTT_meanHits                 INTT_meanHits                 INTT avg. hits                units                             'F'    [0,93]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPnew : public IClassifierReader {

 public:

   // constructor
   ReadMLPnew( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLPnew" ),
        fNvars( 4 )
   {
      // the training input variables
      const char* inputVars[] = { "max(track_1_IP,track_2_IP)", "max(abs(track_1_IP_xy),abs(track_2_IP_xy))", "track_1_track_2_DCA", "INTT_meanHits" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPnew() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][4];
   double fScal_1[3][4];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[15][5];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][15];   // weight matrix from layer 1 to 2

};

inline void ReadMLPnew::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.371270017742686;
   fWeightMatrix0to1[1][0] = 1.7706044423266;
   fWeightMatrix0to1[2][0] = 8.85034476272466;
   fWeightMatrix0to1[3][0] = 0.924328409008795;
   fWeightMatrix0to1[4][0] = -1.63470086717199;
   fWeightMatrix0to1[5][0] = -1.38327094346314;
   fWeightMatrix0to1[6][0] = 0.790241163419693;
   fWeightMatrix0to1[7][0] = 4.901736345446;
   fWeightMatrix0to1[8][0] = 0.018716727029684;
   fWeightMatrix0to1[9][0] = -0.948170278427112;
   fWeightMatrix0to1[10][0] = -0.312912878308065;
   fWeightMatrix0to1[11][0] = 1.04508957646327;
   fWeightMatrix0to1[12][0] = -1.28950287560597;
   fWeightMatrix0to1[13][0] = -1.77048436582237;
   fWeightMatrix0to1[0][1] = -1.69168540540321;
   fWeightMatrix0to1[1][1] = 0.714828096779357;
   fWeightMatrix0to1[2][1] = 4.66267105393972;
   fWeightMatrix0to1[3][1] = 0.959704657855793;
   fWeightMatrix0to1[4][1] = 1.43739718535443;
   fWeightMatrix0to1[5][1] = 1.34319766207685;
   fWeightMatrix0to1[6][1] = -1.73412006454761;
   fWeightMatrix0to1[7][1] = 0.103214066908003;
   fWeightMatrix0to1[8][1] = 0.592676290122851;
   fWeightMatrix0to1[9][1] = -0.114018136019056;
   fWeightMatrix0to1[10][1] = 0.194105805540034;
   fWeightMatrix0to1[11][1] = 0.624177892237752;
   fWeightMatrix0to1[12][1] = 1.71732503026765;
   fWeightMatrix0to1[13][1] = -2.09324808031756;
   fWeightMatrix0to1[0][2] = -2.30489691537058;
   fWeightMatrix0to1[1][2] = 0.0667223243786911;
   fWeightMatrix0to1[2][2] = -0.044951481188298;
   fWeightMatrix0to1[3][2] = 0.299313324362303;
   fWeightMatrix0to1[4][2] = -3.76254878333605;
   fWeightMatrix0to1[5][2] = -0.132620702387949;
   fWeightMatrix0to1[6][2] = 0.492688487613024;
   fWeightMatrix0to1[7][2] = -0.0872273658076029;
   fWeightMatrix0to1[8][2] = -0.20536823401227;
   fWeightMatrix0to1[9][2] = 1.59851054104555;
   fWeightMatrix0to1[10][2] = 0.211968624661105;
   fWeightMatrix0to1[11][2] = 0.811910894269588;
   fWeightMatrix0to1[12][2] = 0.447295320986063;
   fWeightMatrix0to1[13][2] = -0.0788413828958315;
   fWeightMatrix0to1[0][3] = 0.138462425960674;
   fWeightMatrix0to1[1][3] = 1.30817671579522;
   fWeightMatrix0to1[2][3] = 0.296894156804524;
   fWeightMatrix0to1[3][3] = -1.37924684322792;
   fWeightMatrix0to1[4][3] = -0.300113690750916;
   fWeightMatrix0to1[5][3] = -0.106768886795979;
   fWeightMatrix0to1[6][3] = 0.523243735326475;
   fWeightMatrix0to1[7][3] = 0.263751223946695;
   fWeightMatrix0to1[8][3] = 4.39310071154711;
   fWeightMatrix0to1[9][3] = 0.679174593843537;
   fWeightMatrix0to1[10][3] = -3.06099647360978;
   fWeightMatrix0to1[11][3] = 0.657959885057513;
   fWeightMatrix0to1[12][3] = -0.972902308462804;
   fWeightMatrix0to1[13][3] = -2.25841040863338;
   fWeightMatrix0to1[0][4] = -3.0329522856525;
   fWeightMatrix0to1[1][4] = -2.20972874165338;
   fWeightMatrix0to1[2][4] = 13.1479419758704;
   fWeightMatrix0to1[3][4] = 0.815659600799068;
   fWeightMatrix0to1[4][4] = -4.00407814730395;
   fWeightMatrix0to1[5][4] = -0.0676116494636533;
   fWeightMatrix0to1[6][4] = -0.975150440233607;
   fWeightMatrix0to1[7][4] = 4.23770153459808;
   fWeightMatrix0to1[8][4] = 4.77875155056132;
   fWeightMatrix0to1[9][4] = 1.01949141227115;
   fWeightMatrix0to1[10][4] = -2.06107769438511;
   fWeightMatrix0to1[11][4] = -2.54106696459123;
   fWeightMatrix0to1[12][4] = 0.0687823820410542;
   fWeightMatrix0to1[13][4] = -5.92121191119336;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.621509855707168;
   fWeightMatrix1to2[0][1] = 0.730121868385032;
   fWeightMatrix1to2[0][2] = 2.72002615212586;
   fWeightMatrix1to2[0][3] = -0.110318549183625;
   fWeightMatrix1to2[0][4] = 1.27445226847816;
   fWeightMatrix1to2[0][5] = 0.0565701746288308;
   fWeightMatrix1to2[0][6] = -0.63427021171353;
   fWeightMatrix1to2[0][7] = -0.509103185500456;
   fWeightMatrix1to2[0][8] = 1.47592612258331;
   fWeightMatrix1to2[0][9] = 0.23839821537841;
   fWeightMatrix1to2[0][10] = 0.54206934271779;
   fWeightMatrix1to2[0][11] = 2.09060833313788;
   fWeightMatrix1to2[0][12] = -0.212155780718553;
   fWeightMatrix1to2[0][13] = -0.678193913202105;
   fWeightMatrix1to2[0][14] = -2.94224644247805;
}

inline double ReadMLPnew::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)4) {
      std::cout << "Input vector needs to be of size " << 4 << std::endl;
      return 0;
   }

   std::array<double, 15> fWeights1 {{}};
   std::array<double, 1> fWeights2 {{}};
   fWeights1.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<14; o++) {
      std::array<double, 5> buffer; // no need to initialise
      for (int i = 0; i<5 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][4];
      for (int i=0; i<5; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<14; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<1; o++) {
      std::array<double, 15> buffer; // no need to initialise
      for (int i=0; i<15; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<15; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights2[o] = OutputActivationFnc(fWeights2[o]);
   } // loop over o

   return fWeights2[0];
}

double ReadMLPnew::ActivationFnc(double x) const {
   // fast hyperbolic tan approximation
   if (x > 4.97) return 1;
   if (x < -4.97) return -1;
   float x2 = x * x;
   float a = x * (135135.0f + x2 * (17325.0f + x2 * (378.0f + x2)));
   float b = 135135.0f + x2 * (62370.0f + x2 * (3150.0f + x2 * 28.0f));
   return a / b;
}
double ReadMLPnew::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLPnew::Clear()
{
}
inline double ReadMLPnew::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLPnew::InitTransform_1()
{
   double fMin_1[3][4];
   double fMax_1[3][4];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0262883696705;
   fMax_1[0][0] = 4.92083930969;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 0.00383873376995;
   fMax_1[1][0] = 4.99581956863;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 0.00383873376995;
   fMax_1[2][0] = 4.99581956863;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.00748753221706;
   fMax_1[0][1] = 4.8996257782;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 9.33057162911e-05;
   fMax_1[1][1] = 4.55496644974;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 9.33057162911e-05;
   fMax_1[2][1] = 4.8996257782;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 3.39120670105e-05;
   fMax_1[0][2] = 0.0499259270728;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 1.57269468559e-07;
   fMax_1[1][2] = 0.0499997623265;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 1.57269468559e-07;
   fMax_1[2][2] = 0.0499997623265;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 1;
   fMax_1[0][3] = 70;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 93;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 93;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
}

//_______________________________________________________________________
inline void ReadMLPnew::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 4;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<4;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLPnew::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPnew::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
