# -----------------------------------------------------------------------------
# @file   MakeCorrelatorResponseTreeOnCondor.job
# @author Derek Anderson
# @date   05.16.2024
#
# Job file to run standalone correlator response maker via condor.
# -----------------------------------------------------------------------------

# generic parameters
Universe     = vanilla
notification = Never

# executable parameters
Executable           = MakeCorrelatorResponseTreeOnCondor.sh
Initialdir           = ./
request_memory       = 8GB
transfer_input_files = MakeCorrelatorResponseTree.cxx,CorrelatorResponseMakerOptions.h

# output parameters
Output = /sphenix/user/danderson/eec/SCorrelatorResponseMaker/log/testCalc.out
Error  = /sphenix/user/danderson/eec/SCorrelatorResponseMaker/log/testCalc.err
Log    = /sphenix/user/danderson/eec/SCorrelatorResponseMaker/log/testCalc.log

# queue jobs
Queue

# end -------------------------------------------------------------------------

