## the only absolutely essential bits in this file
## are "Executable" and "Queue", but all the rest
## seemed so commonly useful that they are here anyway.

## Executable names the file that you want to run, and
## Input/Output/Error are files for stdin/stdout/stderr.
## Log is a file for diagnostic output from condor
## ...you can use the logfiles to tell you when jobs have completed,
## ...or you can run "$ condor_q | grep $USER"
## $(Process) goes like 0, 1, 2, ..., etc;
## it can be used to label individual jobs.

Initialdir = /sphenix/user/jordan/sphenix-git/analysis/Test/condor
Executable = $(Initialdir)/fiddle
Input      = /dev/null
Output     = $(Initialdir)/out/$(Process)
Error      = $(Initialdir)/err/$(Process)
Log        = $(Initialdir)/log/$(Process)

## if you ain't in no hurry, set Nice_User to True.

Rank = CPU_Speed
Nice_User = True

## boilerplate...
## if you are on PHENIX, use "phenix" instead of "star"
## the PeriodicHold thing makes sure that
## none of your crappy jobs that cannot run
## hold the whole RCF up... to try to resubmit a job
## that gets held up, use condor_release.

+Experiment = "star"
+Job_Type = "cas"
PeriodicHold = (NumJobStarts<=1 && JobStatus == 1)

## there are lots of cool ways to specify multiple jobs using Queue.
## run "$ man condor_submit" for lots of good information.

Queue Arguments In A B C D E F G
