Universe           = vanilla
Executable         = runHFreco.sh
getenv          = True
Output          = /sphenix/tg/tg01/hf/mjpeters/LightFlavorProduction/data/logs/run82420_$(Process).out
Error           = /sphenix/tg/tg01/hf/mjpeters/LightFlavorProduction/data/logs/run82420_$(Process).err
Log             = /sphenix/tg/tg01/hf/mjpeters/LightFlavorProduction/data/logs/run82420_$(Process).log
Initialdir      = .
PeriodicHold    = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 6GB
Priority           = 20
job_lease_duration = 3600
Arguments          = $(events) $(file) $(path) $(skip)
Queue events file path skip from fileLists/file_run82420_0.list
