Universe	= vanilla
Executable 	= EMJetVal_Script.sh
notification 	= Never
Output  	= /sphenix/user/jamesj3j3/analysis/JS-Jet/JetValidation/macro/condorTest/logs/condor$(process).out
Error           = /sphenix/user/jamesj3j3/analysis/JS-Jet/JetValidation/macro/condorTest/logs/condor$(process).err
Log  		= /tmp/condor_jamesj3j3_$(process).log
Arguments 	= "$(Process)"	
Initialdir  	= /sphenix/user/jamesj3j3/analysis/JS-Jet/JetValidation/macro/
request_memory = 4096MB
PeriodicHold = (NumJobStarts>=1 && JobStatus == 1)
Queue 100