/********************************************************************
* ExampleAnalysisModule_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ExampleAnalysisModule_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableExampleAnalysisModule_Dict();
extern void G__cpp_setup_inheritanceExampleAnalysisModule_Dict();
extern void G__cpp_setup_typetableExampleAnalysisModule_Dict();
extern void G__cpp_setup_memvarExampleAnalysisModule_Dict();
extern void G__cpp_setup_globalExampleAnalysisModule_Dict();
extern void G__cpp_setup_memfuncExampleAnalysisModule_Dict();
extern void G__cpp_setup_funcExampleAnalysisModule_Dict();
extern void G__set_cpp_environmentExampleAnalysisModule_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ExampleAnalysisModule.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_TClass;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_TBuffer;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_TMemberInspector;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_TObject;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_string;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_Fun4AllBase;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_PHCompositeNode;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_SubsysReco;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_pairlEintcOintgR;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_Fun4AllHistoManager;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_RawTowerContainer;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_ExampleAnalysisModule;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_ExampleAnalysisModulecLcLEval_Run;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_ExampleAnalysisModulecLcLEval_Cluster;
extern G__linked_taginfo G__ExampleAnalysisModule_DictLN_ExampleAnalysisModulecLcLdA;

/* STUB derived class for protected member access */
