Universe 	= vanilla
Executable 	= run_smd.sh
notification 	= Never
Arguments       = $(Process)
Output  	= log/condordloom_$(process).out
Error           = log/condordloom_$(process).err
Log  		= /tmp/condordloom_$(process).log
Initialdir  	= /sphenix/user/dloomis/analysis/ZDCNeutronLocPol/macros
# Jobs by default use 1.5Gb of RAM, you need to ask for more if needed
# with request_memory. Be mindful - if you request too little your jobs will be evicted, if you request way too much it will take longer for your job to start
#request_memory = 4096MB
# the importance of this PeriodicHold will be explained in the next section
PeriodicHold = (NumJobStarts>=1 && JobStatus == 1)
Queue 500