Universe           = vanilla
Executable         = get_singletrack_abundance.sh
getenv          = True
Output          = /sphenix/tg/tg01/hf/mjpeters/LightFlavorProduction/single_track_histograms/simulation/logs/singletrack_$(Process).out
Error           = /sphenix/tg/tg01/hf/mjpeters/LightFlavorProduction/single_track_histograms/simulation/logs/singletrack_$(Process).err
Log             = /sphenix/tg/tg01/hf/mjpeters/LightFlavorProduction/single_track_histograms/simulation/logs/singletrack_$(Process).log
Initialdir      = /sphenix/user/mjpeters/analysis/LightFlavorRatios/single_track_abundance
PeriodicHold    = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 8GB
Priority           = 20
job_lease_duration = 3600
Arguments          = $(infile) /sphenix/tg/tg01/hf/mjpeters/LightFlavorProduction/single_track_histograms/simulation/singletrack_output_$(Process).root
Queue infile matching /sphenix/tg/tg01/hf/mjpeters/LightFlavorProduction/simulation/nTP/*.root
