#! /bin/bash

# Beam spot reconstruction
python runCondor_beamspot.py --isdata --infiledir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/production/Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --outfiledir BeamspotMinitree_data_Run20869_HotDead_BCO_ADC_Survey --dphicut 0.122 --nJob 549  
python runCondor_beamspot.py --infiledir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/production/Sim_Ntuple_HIJING_new_20240424 --outfiledir BeamspotMinitree_Sim_HIJING_new_20240424 --dphicut 0.122 --nJob 200

# Vertex Z reconstruction

# Tracklet reconstruction
# # Data - Different deltaR cut
# python runCondor_recotracklet.py --isdata --filedesc Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --nEvents 1000 --nJob 549 --drcut 0.5 --randomclusset 0 --clusadccutset 0
# python runCondor_recotracklet.py --isdata --filedesc Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --nEvents 1000 --nJob 549 --drcut 0.4 --randomclusset 0 --clusadccutset 0
# python runCondor_recotracklet.py --isdata --filedesc Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --nEvents 1000 --nJob 549 --drcut 0.6 --randomclusset 0 --clusadccutset 0
# # Data - Different cluster adc cut
# python runCondor_recotracklet.py --isdata --filedesc Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --nEvents 1000 --nJob 549 --drcut 0.5 --randomclusset 0 --clusadccutset 1
# python runCondor_recotracklet.py --isdata --filedesc Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --nEvents 1000 --nJob 549 --drcut 0.5 --randomclusset 0 --clusadccutset 2
# # Simulation - Different deltaR cut
# python runCondor_recotracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nEvents 400 --nJob 200 --drcut 0.5 --randomclusset 0 --clusadccutset 0
# python runCondor_recotracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nEvents 400 --nJob 200 --drcut 0.4 --randomclusset 0 --clusadccutset 0
# python runCondor_recotracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nEvents 400 --nJob 200 --drcut 0.6 --randomclusset 0 --clusadccutset 0
# # Simulation - Different cluster adc cut
# python runCondor_recotracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nEvents 400 --nJob 200 --drcut 0.5 --randomclusset 0 --clusadccutset 1
# python runCondor_recotracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nEvents 400 --nJob 200 --drcut 0.5 --randomclusset 0 --clusadccutset 2
# # Simulation - Different random cluster set
# python runCondor_recotracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nEvents 400 --nJob 200 --drcut 0.5 --randomclusset 1 --clusadccutset 0
# python runCondor_recotracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nEvents 400 --nJob 200 --drcut 0.5 --randomclusset 2 --clusadccutset 0
# python runCondor_recotracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nEvents 400 --nJob 200 --drcut 0.5 --randomclusset 3 --clusadccutset 0
# python runCondor_recotracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nEvents 400 --nJob 200 --drcut 0.5 --randomclusset 4 --clusadccutset 0

# Plot reconstructed vertex 

# Plot TrkrHit

# Plot reconstructed cluster

# # Plot reconstructed tracklet
# # Data - Different deltaR cut
# python runCondor_plotTracklet.py --isdata --filedesc Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --nJob 549 --drcut 0.5 --randomclusset 0 --clusadccutset 0 --submitcondor
# python runCondor_plotTracklet.py --isdata --filedesc Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --nJob 549 --drcut 0.4 --randomclusset 0 --clusadccutset 0 --submitcondor
# python runCondor_plotTracklet.py --isdata --filedesc Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --nJob 549 --drcut 0.6 --randomclusset 0 --clusadccutset 0 --submitcondor
# # Data - Different cluster adc cut
# python runCondor_plotTracklet.py --isdata --filedesc Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --nJob 549 --drcut 0.5 --randomclusset 0 --clusadccutset 1 --submitcondor
# python runCondor_plotTracklet.py --isdata --filedesc Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey --nJob 549 --drcut 0.5 --randomclusset 0 --clusadccutset 2 --submitcondor
# # Simulation - Different deltaR cut
# python runCondor_plotTracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nJob 200 --drcut 0.5 --randomclusset 0 --clusadccutset 0 --submitcondor
# python runCondor_plotTracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nJob 200 --drcut 0.4 --randomclusset 0 --clusadccutset 0 --submitcondor
# python runCondor_plotTracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nJob 200 --drcut 0.6 --randomclusset 0 --clusadccutset 0 --submitcondor
# # Simulation - Different cluster adc cut
# python runCondor_plotTracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nJob 200 --drcut 0.5 --randomclusset 0 --clusadccutset 1 --submitcondor
# python runCondor_plotTracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nJob 200 --drcut 0.5 --randomclusset 0 --clusadccutset 2 --submitcondor
# # Simulation - Different random cluster set
# python runCondor_plotTracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nJob 200 --drcut 0.5 --randomclusset 1 --clusadccutset 0 --submitcondor
# python runCondor_plotTracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nJob 200 --drcut 0.5 --randomclusset 2 --clusadccutset 0 --submitcondor
# python runCondor_plotTracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nJob 200 --drcut 0.5 --randomclusset 3 --clusadccutset 0 --submitcondor
# python runCondor_plotTracklet.py --filedesc Sim_Ntuple_HIJING_new_20240424 --nJob 200 --drcut 0.5 --randomclusset 4 --clusadccutset 0 --submitcondor

# # Corrections
# # Different deltaR cut
# python runCondor_corrections.py --corrfiletag HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --outfilepathbaseline HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --outfilepathclosure HIJING_closure_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --outfilepathdata Data_Run20869_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --hijingbaselinedir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --hijingclosuredir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --datadir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --submitcondor
# python runCondor_corrections.py --corrfiletag HIJING_Baseline_dRcut0p4_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --outfilepathbaseline HIJING_Baseline_dRcut0p4_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --outfilepathclosure HIJING_closure_dRcut0p4_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --outfilepathdata Data_Run20869_dRcut0p4_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --hijingbaselinedir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p4_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --hijingclosuredir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p4_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --datadir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/dRcut0p4_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --submitcondor
# python runCondor_corrections.py --corrfiletag HIJING_Baseline_dRcut0p6_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --outfilepathbaseline HIJING_Baseline_dRcut0p6_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --outfilepathclosure HIJING_closure_dRcut0p6_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --outfilepathdata Data_Run20869_dRcut0p6_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --hijingbaselinedir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p6_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --hijingclosuredir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p6_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --datadir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/dRcut0p6_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --submitcondor
# # Different cluster adc cut
# python runCondor_corrections.py --corrfiletag HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet1 --outfilepathbaseline HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet1 --outfilepathclosure HIJING_closure_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet1 --outfilepathdata Data_Run20869_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet1 --hijingbaselinedir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet1 --hijingclosuredir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet1 --datadir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet1 --submitcondor
# python runCondor_corrections.py --corrfiletag HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet2 --outfilepathbaseline HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet2 --outfilepathclosure HIJING_closure_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet2 --outfilepathdata Data_Run20869_dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet2 --hijingbaselinedir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet2 --hijingclosuredir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet2 --datadir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet2 --submitcondor
# # Different random cluster set (derive the correction factors with different random cluster set, apply the correction factors to the simulation closure events and data for the baseline)
# python runCondor_corrections.py --corrfiletag HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet1_clusAdcCutSet0 --outfilepathbaseline HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet1_clusAdcCutSet0 --outfilepathclosure HIJING_closure_dRcut0p5_NominalVtxZ_RandomClusSet1_clusAdcCutSet0 --outfilepathdata Data_Run20869_dRcut0p5_NominalVtxZ_RandomClusSet1_clusAdcCutSet0 --hijingbaselinedir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet1_clusAdcCutSet0 --hijingclosuredir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --datadir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --submitcondor
# python runCondor_corrections.py --corrfiletag HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet2_clusAdcCutSet0 --outfilepathbaseline HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet2_clusAdcCutSet0 --outfilepathclosure HIJING_closure_dRcut0p5_NominalVtxZ_RandomClusSet2_clusAdcCutSet0 --outfilepathdata Data_Run20869_dRcut0p5_NominalVtxZ_RandomClusSet2_clusAdcCutSet0 --hijingbaselinedir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet2_clusAdcCutSet0 --hijingclosuredir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --datadir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --submitcondor
# python runCondor_corrections.py --corrfiletag HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet3_clusAdcCutSet0 --outfilepathbaseline HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet3_clusAdcCutSet0 --outfilepathclosure HIJING_closure_dRcut0p5_NominalVtxZ_RandomClusSet3_clusAdcCutSet0 --outfilepathdata Data_Run20869_dRcut0p5_NominalVtxZ_RandomClusSet3_clusAdcCutSet0 --hijingbaselinedir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet3_clusAdcCutSet0 --hijingclosuredir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --datadir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --submitcondor
# python runCondor_corrections.py --corrfiletag HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet4_clusAdcCutSet0 --outfilepathbaseline HIJING_Baseline_dRcut0p5_NominalVtxZ_RandomClusSet4_clusAdcCutSet0 --outfilepathclosure HIJING_closure_dRcut0p5_NominalVtxZ_RandomClusSet4_clusAdcCutSet0 --outfilepathdata Data_Run20869_dRcut0p5_NominalVtxZ_RandomClusSet4_clusAdcCutSet0 --hijingbaselinedir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet4_clusAdcCutSet0 --hijingclosuredir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Sim_Ntuple_HIJING_new_20240424/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --datadir /sphenix/user/hjheng/sPHENIXRepo/analysis/dNdEta_Run2023/analysis_INTT/minitree/TrackletMinitree_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey/dRcut0p5_NominalVtxZ_RandomClusSet0_clusAdcCutSet0 --submitcondor
