Universe           = vanilla
Initialdir         = /sphenix/user/ChengWei/INTT/INTT_dNdeta_repo/NewCode2024/InttVtxZQA_Bias/macro
Executable         = run_job.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:100
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400

runnumber          = 54280
nEvents            = -1
input_directory    = /sphenix/tg/tg01/commissioning/INTT/work/cwshih/seflgendata/run_54280_HR_Feb102025/Run6_EvtZFitWidthChange/EvtVtxZ/completed
job_offset    = 0
process_shift      = $(Process) + $(job_offset) 
input_filename     = Data_EvtVtxZProtoTracklet_FieldOff_BcoFullDiff_VtxZReco_00054280_$INT(process_shift,%05d).root
output_directory   = /sphenix/tg/tg01/commissioning/INTT/work/cwshih/seflgendata/run_54280_HR_Feb102025/Run6_EvtZFitWidthChange/EvtVtxZ/completed/VtxZQABias

Output             = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).out
Error              = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).err
Log                = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).log
Arguments          = "$INT(process_shift) $(runnumber) $(nEvents) $(output_directory) $(input_directory) $(input_filename)"
Queue 1758