//
// File generated by rootcint at Wed Jul 24 11:48:35 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ExclusiveReco_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ExclusiveReco_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void ExclusiveReco_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void ExclusiveReco_Dictionary();
   static void delete_ExclusiveReco(void *p);
   static void deleteArray_ExclusiveReco(void *p);
   static void destruct_ExclusiveReco(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::ExclusiveReco*)
   {
      ::ExclusiveReco *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::ExclusiveReco),0);
      static ::ROOT::TGenericClassInfo 
         instance("ExclusiveReco", "./ExclusiveReco.h", 33,
                  typeid(::ExclusiveReco), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &ExclusiveReco_Dictionary, isa_proxy, 1,
                  sizeof(::ExclusiveReco) );
      instance.SetDelete(&delete_ExclusiveReco);
      instance.SetDeleteArray(&deleteArray_ExclusiveReco);
      instance.SetDestructor(&destruct_ExclusiveReco);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::ExclusiveReco*)
   {
      return GenerateInitInstanceLocal((::ExclusiveReco*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ExclusiveReco*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void ExclusiveReco_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::ExclusiveReco*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_ExclusiveReco(void *p) {
      delete ((::ExclusiveReco*)p);
   }
   static void deleteArray_ExclusiveReco(void *p) {
      delete [] ((::ExclusiveReco*)p);
   }
   static void destruct_ExclusiveReco(void *p) {
      typedef ::ExclusiveReco current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::ExclusiveReco

/********************************************************
* ExclusiveReco_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableExclusiveReco_Dict();

extern "C" void G__set_cpp_environmentExclusiveReco_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ExclusiveReco.h");
  G__cpp_reset_tagtableExclusiveReco_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevExclusiveReco_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ExclusiveReco */
static int G__ExclusiveReco_Dict_634_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ExclusiveReco* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new ExclusiveReco(*((string*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) ExclusiveReco(*((string*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_ExclusiveReco));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExclusiveReco_Dict_634_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ExclusiveReco*) G__getstructoffset())->set_beam_energies((float) G__double(libp->para[0]), (float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExclusiveReco_Dict_634_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ExclusiveReco*) G__getstructoffset())->set_do_process_dvmp((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ExclusiveReco_Dict_634_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ExclusiveReco* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ExclusiveReco(*(ExclusiveReco*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_ExclusiveReco));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ExclusiveReco G__TExclusiveReco;
static int G__ExclusiveReco_Dict_634_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ExclusiveReco*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ExclusiveReco*) (soff+(sizeof(ExclusiveReco)*i)))->~G__TExclusiveReco();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ExclusiveReco*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ExclusiveReco*) (soff))->~G__TExclusiveReco();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ExclusiveReco */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncExclusiveReco_Dict {
 public:
  G__Sizep2memfuncExclusiveReco_Dict(): p(&G__Sizep2memfuncExclusiveReco_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncExclusiveReco_Dict::*p)();
};

size_t G__get_sizep2memfuncExclusiveReco_Dict()
{
  G__Sizep2memfuncExclusiveReco_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceExclusiveReco_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ExclusiveReco_DictLN_ExclusiveReco))) {
     ExclusiveReco *G__Lderived;
     G__Lderived=(ExclusiveReco*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ExclusiveReco_DictLN_ExclusiveReco),G__get_linked_tagnum(&G__ExclusiveReco_DictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ExclusiveReco_DictLN_ExclusiveReco),G__get_linked_tagnum(&G__ExclusiveReco_DictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableExclusiveReco_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<float,SvtxTrackState*>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<float,SvtxTrackState*,less<float> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned int>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned int,less<unsigned int> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<TrkrDefs::cluskey>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_setlEunsignedsPlongcOlesslEunsignedsPlonggRcOallocatorlEunsignedsPlonggRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned long>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_setlEunsignedsPlongcOlesslEunsignedsPlonggRcOallocatorlEunsignedsPlonggRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned long,less<unsigned long> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_setlEunsignedsPlongcOlesslEunsignedsPlonggRcOallocatorlEunsignedsPlonggRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,SvtxTrack*>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEunsignedsPintcOSvtxTrackmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxTrackmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,SvtxTrack*,less<unsigned int> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEunsignedsPintcOSvtxTrackmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxTrackmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<CAL_LAYER,float>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOfloatcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SvtxTrack::CAL_LAYER,float>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOfloatcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SvtxTrack::CAL_LAYER,float,less<SvtxTrack::CAL_LAYER> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOfloatcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<CAL_LAYER,int>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOintcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SvtxTrack::CAL_LAYER,int>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOintcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SvtxTrack::CAL_LAYER,int,less<SvtxTrack::CAL_LAYER> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOintcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<CAL_LAYER,TrkrDefs::cluskey>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOunsignedsPlongcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SvtxTrack::CAL_LAYER,unsigned long>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOunsignedsPlongcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SvtxTrack::CAL_LAYER,unsigned long,less<SvtxTrack::CAL_LAYER> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOunsignedsPlongcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,PHHepMCGenEvent*>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEintcOPHHepMCGenEventmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOPHHepMCGenEventmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,PHHepMCGenEvent*,less<int> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEintcOPHHepMCGenEventmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOPHHepMCGenEventmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,size_type>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,size_type>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,unsigned long>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,unsigned long,less<string> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<HepMC::GenParticle*>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::forward_iterator_tag,HepMC::GenParticle*,ptrdiff_t>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenParticle*,ptrdiff_t>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenParticle*>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenParticle*,long>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenParticle*,long,HepMC::GenParticle**>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::forward_iterator_tag,HepMC::GenVertex*,ptrdiff_t>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenVertex*,ptrdiff_t>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenVertex*>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenVertex*,long>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<forward_iterator_tag,HepMC::GenVertex*,long,HepMC::GenVertex**>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<const HepMC::GenVertex*>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<const HepMC::GenVertex*,less<const HepMC::GenVertex*> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenVertex*,std::greater<int> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenVertex*>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenVertex*,greater<int> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenParticle*>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenParticle*,less<int> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,HepMC::GenParticle*,std::less<int> >",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ExclusiveReco */
static void G__setup_memvarExclusiveReco(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ExclusiveReco_DictLN_ExclusiveReco));
   { ExclusiveReco *p; p=(ExclusiveReco*)0x1000; if (p) { }
   G__memvar_setup((void*)0,102,0,1,-1,-1,-1,4,"_mproton=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_verbose=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_save_towers=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_save_tracks=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_do_process_dvmp=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_ievent=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_total_pass=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_string),-1,-1,4,"_filename=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_TFile),-1,-1,4,"_tfile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_TTree),-1,-1,4,"_tree_invariant_mass=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_TTree),-1,-1,4,"_tree_event_reco=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_TTree),-1,-1,4,"_tree_event_truth=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"_beam_electron_ptotal=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"_beam_hadron_ptotal=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_TrackProjectorPlaneECAL),-1,-1,4,"_trackproj=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_PHCompositeNode),-1,-1,4,"_topNode=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"true_eta=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"true_phi=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"true_ptotal=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"true_pid=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<bool>"),-1,4,"is_scattered_lepton=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"reco_eta=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"reco_phi=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"reco_ptotal=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"reco_cluster_e=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"reco_charge=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<bool>"),-1,4,"reco_is_scattered_lepton=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"_vect1=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"_vect2=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"_vect3=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"_vect4=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"_vect5=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"_vect6=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarExclusiveReco_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncExclusiveReco(void) {
   /* ExclusiveReco */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ExclusiveReco_DictLN_ExclusiveReco));
   G__memfunc_setup("ExclusiveReco",1345,G__ExclusiveReco_Dict_634_0_1, 105, G__get_linked_tagnum(&G__ExclusiveReco_DictLN_ExclusiveReco), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_beam_energies",1777,G__ExclusiveReco_Dict_634_0_6, 121, -1, -1, 0, 2, 1, 1, 0, 
"f - - 0 - beam_electron f - - 0 - beam_proton", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_do_process_dvmp",2034,G__ExclusiveReco_Dict_634_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - select", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddInvariantMassInformation",2767,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("ExclusiveReco", 1345, G__ExclusiveReco_Dict_634_0_9, (int) ('i'), G__get_linked_tagnum(&G__ExclusiveReco_DictLN_ExclusiveReco), -1, 0, 1, 1, 1, 0, "u 'ExclusiveReco' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ExclusiveReco", 1471, G__ExclusiveReco_Dict_634_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncExclusiveReco_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalExclusiveReco_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcExclusiveReco_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_vectorlEboolcOallocatorlEboolgRsPgR = { "vector<bool,allocator<bool> >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR = { "map<float,SvtxTrackState*,less<float>,allocator<pair<const float,SvtxTrackState*> > >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR = { "set<unsigned int,less<unsigned int>,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_setlEunsignedsPlongcOlesslEunsignedsPlonggRcOallocatorlEunsignedsPlonggRsPgR = { "set<unsigned long,less<unsigned long>,allocator<unsigned long> >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_maplEunsignedsPintcOSvtxTrackmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxTrackmUgRsPgRsPgR = { "map<unsigned int,SvtxTrack*,less<unsigned int>,allocator<pair<const unsigned int,SvtxTrack*> > >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOfloatcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOfloatgRsPgRsPgR = { "map<SvtxTrack::CAL_LAYER,float,less<SvtxTrack::CAL_LAYER>,allocator<pair<const SvtxTrack::CAL_LAYER,float> > >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOintcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOintgRsPgRsPgR = { "map<SvtxTrack::CAL_LAYER,int,less<SvtxTrack::CAL_LAYER>,allocator<pair<const SvtxTrack::CAL_LAYER,int> > >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOunsignedsPlongcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOunsignedsPlonggRsPgRsPgR = { "map<SvtxTrack::CAL_LAYER,unsigned long,less<SvtxTrack::CAL_LAYER>,allocator<pair<const SvtxTrack::CAL_LAYER,unsigned long> > >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_TrackProjectorPlaneECAL = { "TrackProjectorPlaneECAL" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_maplEintcOPHHepMCGenEventmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOPHHepMCGenEventmUgRsPgRsPgR = { "map<int,PHHepMCGenEvent*,less<int>,allocator<pair<const int,PHHepMCGenEvent*> > >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR = { "map<string,unsigned long,less<string>,allocator<pair<const string,unsigned long> > >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR = { "vector<HepMC::GenParticle*,allocator<HepMC::GenParticle*> >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<HepMC::GenParticle*,allocator<HepMC::GenParticle*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR = { "iterator<forward_iterator_tag,HepMC::GenParticle*,long,HepMC::GenParticle**,HepMC::GenParticle*&>" , 115 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR = { "iterator<forward_iterator_tag,HepMC::GenVertex*,long,HepMC::GenVertex**,HepMC::GenVertex*&>" , 115 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR = { "set<const HepMC::GenVertex*,less<const HepMC::GenVertex*>,allocator<const HepMC::GenVertex*> >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR = { "map<int,HepMC::GenVertex*,greater<int>,allocator<pair<const int,HepMC::GenVertex*> > >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR = { "map<int,HepMC::GenParticle*,less<int>,allocator<pair<const int,HepMC::GenParticle*> > >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_ExclusiveReco = { "ExclusiveReco" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableExclusiveReco_Dict() {
  G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_vectorlEboolcOallocatorlEboolgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_string.tagnum = -1 ;
  G__ExclusiveReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_setlEunsignedsPlongcOlesslEunsignedsPlonggRcOallocatorlEunsignedsPlonggRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_maplEunsignedsPintcOSvtxTrackmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxTrackmUgRsPgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOfloatcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOfloatgRsPgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOintcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOintgRsPgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOunsignedsPlongcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOunsignedsPlonggRsPgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_PHCompositeNode.tagnum = -1 ;
  G__ExclusiveReco_DictLN_TrackProjectorPlaneECAL.tagnum = -1 ;
  G__ExclusiveReco_DictLN_Fun4AllBase.tagnum = -1 ;
  G__ExclusiveReco_DictLN_SubsysReco.tagnum = -1 ;
  G__ExclusiveReco_DictLN_maplEintcOPHHepMCGenEventmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOPHHepMCGenEventmUgRsPgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_TTree.tagnum = -1 ;
  G__ExclusiveReco_DictLN_TFile.tagnum = -1 ;
  G__ExclusiveReco_DictLN_ExclusiveReco.tagnum = -1 ;
  G__ExclusiveReco_DictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableExclusiveReco_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_vectorlEboolcOallocatorlEboolgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_string);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_setlEunsignedsPlongcOlesslEunsignedsPlonggRcOallocatorlEunsignedsPlonggRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_maplEunsignedsPintcOSvtxTrackmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxTrackmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOfloatcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOfloatgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOintcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_maplESvtxTrackcLcLCAL_LAYERcOunsignedsPlongcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOunsignedsPlonggRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_TrackProjectorPlaneECAL);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_SubsysReco);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_maplEintcOPHHepMCGenEventmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOPHHepMCGenEventmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_TTree);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_TFile);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_ExclusiveReco),sizeof(ExclusiveReco),-1,98304,(char*)NULL,G__setup_memvarExclusiveReco,G__setup_memfuncExclusiveReco);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExclusiveReco_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupExclusiveReco_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupExclusiveReco_Dict()");
  G__set_cpp_environmentExclusiveReco_Dict();
  G__cpp_setup_tagtableExclusiveReco_Dict();

  G__cpp_setup_inheritanceExclusiveReco_Dict();

  G__cpp_setup_typetableExclusiveReco_Dict();

  G__cpp_setup_memvarExclusiveReco_Dict();

  G__cpp_setup_memfuncExclusiveReco_Dict();
  G__cpp_setup_globalExclusiveReco_Dict();
  G__cpp_setup_funcExclusiveReco_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncExclusiveReco_Dict();
  return;
}
class G__cpp_setup_initExclusiveReco_Dict {
  public:
    G__cpp_setup_initExclusiveReco_Dict() { G__add_setup_func("ExclusiveReco_Dict",(G__incsetup)(&G__cpp_setupExclusiveReco_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initExclusiveReco_Dict() { G__remove_setup_func("ExclusiveReco_Dict"); }
};
G__cpp_setup_initExclusiveReco_Dict G__cpp_setup_initializerExclusiveReco_Dict;

