/********************************************************************
* Leptoquarks_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Leptoquarks_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLeptoquarks_Dict();
extern void G__cpp_setup_inheritanceLeptoquarks_Dict();
extern void G__cpp_setup_typetableLeptoquarks_Dict();
extern void G__cpp_setup_memvarLeptoquarks_Dict();
extern void G__cpp_setup_globalLeptoquarks_Dict();
extern void G__cpp_setup_memfuncLeptoquarks_Dict();
extern void G__cpp_setup_funcLeptoquarks_Dict();
extern void G__set_cpp_environmentLeptoquarks_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Leptoquarks.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Leptoquarks_DictLN_string;
extern G__linked_taginfo G__Leptoquarks_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Leptoquarks_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Leptoquarks_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Leptoquarks_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Leptoquarks_DictLN_Fun4AllBase;
extern G__linked_taginfo G__Leptoquarks_DictLN_PHCompositeNode;
extern G__linked_taginfo G__Leptoquarks_DictLN_SubsysReco;
extern G__linked_taginfo G__Leptoquarks_DictLN_TNtuple;
extern G__linked_taginfo G__Leptoquarks_DictLN_TFile;
extern G__linked_taginfo G__Leptoquarks_DictLN_HepMC;
extern G__linked_taginfo G__Leptoquarks_DictLN_HepMCcLcLGenParticle;
extern G__linked_taginfo G__Leptoquarks_DictLN_Leptoquarks;

/* STUB derived class for protected member access */
