/********************************************************************
* Quarkonia2LeptonsMC_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Quarkonia2LeptonsMC_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableQuarkonia2LeptonsMC_Dict();
extern void G__cpp_setup_inheritanceQuarkonia2LeptonsMC_Dict();
extern void G__cpp_setup_typetableQuarkonia2LeptonsMC_Dict();
extern void G__cpp_setup_memvarQuarkonia2LeptonsMC_Dict();
extern void G__cpp_setup_globalQuarkonia2LeptonsMC_Dict();
extern void G__cpp_setup_memfuncQuarkonia2LeptonsMC_Dict();
extern void G__cpp_setup_funcQuarkonia2LeptonsMC_Dict();
extern void G__set_cpp_environmentQuarkonia2LeptonsMC_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Quarkonia2LeptonsMC.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_string;
extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_Fun4AllBase;
extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_PHCompositeNode;
extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_SubsysReco;
extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_TNtuple;
extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_TFile;
extern G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC;

/* STUB derived class for protected member access */
