//
// File generated by rootcint at Wed Jul 24 11:48:22 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME Quarkonia2LeptonsMC_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Quarkonia2LeptonsMC_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void Quarkonia2LeptonsMC_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void Quarkonia2LeptonsMC_Dictionary();
   static void delete_Quarkonia2LeptonsMC(void *p);
   static void deleteArray_Quarkonia2LeptonsMC(void *p);
   static void destruct_Quarkonia2LeptonsMC(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::Quarkonia2LeptonsMC*)
   {
      ::Quarkonia2LeptonsMC *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::Quarkonia2LeptonsMC),0);
      static ::ROOT::TGenericClassInfo 
         instance("Quarkonia2LeptonsMC", "./Quarkonia2LeptonsMC.h", 23,
                  typeid(::Quarkonia2LeptonsMC), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &Quarkonia2LeptonsMC_Dictionary, isa_proxy, 1,
                  sizeof(::Quarkonia2LeptonsMC) );
      instance.SetDelete(&delete_Quarkonia2LeptonsMC);
      instance.SetDeleteArray(&deleteArray_Quarkonia2LeptonsMC);
      instance.SetDestructor(&destruct_Quarkonia2LeptonsMC);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::Quarkonia2LeptonsMC*)
   {
      return GenerateInitInstanceLocal((::Quarkonia2LeptonsMC*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Quarkonia2LeptonsMC*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void Quarkonia2LeptonsMC_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::Quarkonia2LeptonsMC*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_Quarkonia2LeptonsMC(void *p) {
      delete ((::Quarkonia2LeptonsMC*)p);
   }
   static void deleteArray_Quarkonia2LeptonsMC(void *p) {
      delete [] ((::Quarkonia2LeptonsMC*)p);
   }
   static void destruct_Quarkonia2LeptonsMC(void *p) {
      typedef ::Quarkonia2LeptonsMC current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::Quarkonia2LeptonsMC

/********************************************************
* Quarkonia2LeptonsMC_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableQuarkonia2LeptonsMC_Dict();

extern "C" void G__set_cpp_environmentQuarkonia2LeptonsMC_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Quarkonia2LeptonsMC.h");
  G__cpp_reset_tagtableQuarkonia2LeptonsMC_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevQuarkonia2LeptonsMC_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Quarkonia2LeptonsMC */
static int G__Quarkonia2LeptonsMC_Dict_192_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Quarkonia2LeptonsMC* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new Quarkonia2LeptonsMC(*((string*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) Quarkonia2LeptonsMC(*((string*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Quarkonia2LeptonsMC_Dict_192_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Quarkonia2LeptonsMC*) G__getstructoffset())->get_embedding_id());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Quarkonia2LeptonsMC_Dict_192_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Quarkonia2LeptonsMC*) G__getstructoffset())->set_embedding_id((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Quarkonia2LeptonsMC_Dict_192_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Quarkonia2LeptonsMC* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Quarkonia2LeptonsMC(*(Quarkonia2LeptonsMC*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Quarkonia2LeptonsMC G__TQuarkonia2LeptonsMC;
static int G__Quarkonia2LeptonsMC_Dict_192_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Quarkonia2LeptonsMC*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Quarkonia2LeptonsMC*) (soff+(sizeof(Quarkonia2LeptonsMC)*i)))->~G__TQuarkonia2LeptonsMC();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Quarkonia2LeptonsMC*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Quarkonia2LeptonsMC*) (soff))->~G__TQuarkonia2LeptonsMC();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Quarkonia2LeptonsMC_Dict_192_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Quarkonia2LeptonsMC* dest = (Quarkonia2LeptonsMC*) G__getstructoffset();
   *dest = *(Quarkonia2LeptonsMC*) libp->para[0].ref;
   const Quarkonia2LeptonsMC& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Quarkonia2LeptonsMC */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncQuarkonia2LeptonsMC_Dict {
 public:
  G__Sizep2memfuncQuarkonia2LeptonsMC_Dict(): p(&G__Sizep2memfuncQuarkonia2LeptonsMC_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncQuarkonia2LeptonsMC_Dict::*p)();
};

size_t G__get_sizep2memfuncQuarkonia2LeptonsMC_Dict()
{
  G__Sizep2memfuncQuarkonia2LeptonsMC_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceQuarkonia2LeptonsMC_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC))) {
     Quarkonia2LeptonsMC *G__Lderived;
     G__Lderived=(Quarkonia2LeptonsMC*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC),G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC),G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableQuarkonia2LeptonsMC_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Quarkonia2LeptonsMC */
static void G__setup_memvarQuarkonia2LeptonsMC(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC));
   { Quarkonia2LeptonsMC *p; p=(Quarkonia2LeptonsMC*)0x1000; if (p) { }
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_verbose=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_ievent=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_total_pass=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_string),-1,-1,4,"_foutname=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_TFile),-1,-1,4,"_fout_root=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_TNtuple),-1,-1,4,"_tree_quarkonia=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_embedding_id=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarQuarkonia2LeptonsMC_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncQuarkonia2LeptonsMC(void) {
   /* Quarkonia2LeptonsMC */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC));
   G__memfunc_setup("Quarkonia2LeptonsMC",1874,G__Quarkonia2LeptonsMC_Dict_192_0_1, 105, G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_embedding_id",1642,G__Quarkonia2LeptonsMC_Dict_192_0_5, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_embedding_id",1654,G__Quarkonia2LeptonsMC_Dict_192_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - id", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("Quarkonia2LeptonsMC", 1874, G__Quarkonia2LeptonsMC_Dict_192_0_7, (int) ('i'), G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC), -1, 0, 1, 1, 1, 0, "u 'Quarkonia2LeptonsMC' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Quarkonia2LeptonsMC", 2000, G__Quarkonia2LeptonsMC_Dict_192_0_8, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Quarkonia2LeptonsMC_Dict_192_0_9, (int) ('u'), G__get_linked_tagnum(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC), -1, 1, 1, 1, 1, 0, "u 'Quarkonia2LeptonsMC' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncQuarkonia2LeptonsMC_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalQuarkonia2LeptonsMC_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcQuarkonia2LeptonsMC_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_TNtuple = { "TNtuple" , 99 , -1 };
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC = { "Quarkonia2LeptonsMC" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableQuarkonia2LeptonsMC_Dict() {
  G__Quarkonia2LeptonsMC_DictLN_string.tagnum = -1 ;
  G__Quarkonia2LeptonsMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Quarkonia2LeptonsMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Quarkonia2LeptonsMC_DictLN_Fun4AllBase.tagnum = -1 ;
  G__Quarkonia2LeptonsMC_DictLN_PHCompositeNode.tagnum = -1 ;
  G__Quarkonia2LeptonsMC_DictLN_SubsysReco.tagnum = -1 ;
  G__Quarkonia2LeptonsMC_DictLN_TNtuple.tagnum = -1 ;
  G__Quarkonia2LeptonsMC_DictLN_TFile.tagnum = -1 ;
  G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableQuarkonia2LeptonsMC_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_string);
   G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_SubsysReco);
   G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_TNtuple);
   G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_TFile);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Quarkonia2LeptonsMC_DictLN_Quarkonia2LeptonsMC),sizeof(Quarkonia2LeptonsMC),-1,98304,(char*)NULL,G__setup_memvarQuarkonia2LeptonsMC,G__setup_memfuncQuarkonia2LeptonsMC);
}
extern "C" void G__cpp_setupQuarkonia2LeptonsMC_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupQuarkonia2LeptonsMC_Dict()");
  G__set_cpp_environmentQuarkonia2LeptonsMC_Dict();
  G__cpp_setup_tagtableQuarkonia2LeptonsMC_Dict();

  G__cpp_setup_inheritanceQuarkonia2LeptonsMC_Dict();

  G__cpp_setup_typetableQuarkonia2LeptonsMC_Dict();

  G__cpp_setup_memvarQuarkonia2LeptonsMC_Dict();

  G__cpp_setup_memfuncQuarkonia2LeptonsMC_Dict();
  G__cpp_setup_globalQuarkonia2LeptonsMC_Dict();
  G__cpp_setup_funcQuarkonia2LeptonsMC_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncQuarkonia2LeptonsMC_Dict();
  return;
}
class G__cpp_setup_initQuarkonia2LeptonsMC_Dict {
  public:
    G__cpp_setup_initQuarkonia2LeptonsMC_Dict() { G__add_setup_func("Quarkonia2LeptonsMC_Dict",(G__incsetup)(&G__cpp_setupQuarkonia2LeptonsMC_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initQuarkonia2LeptonsMC_Dict() { G__remove_setup_func("Quarkonia2LeptonsMC_Dict"); }
};
G__cpp_setup_initQuarkonia2LeptonsMC_Dict G__cpp_setup_initializerQuarkonia2LeptonsMC_Dict;

