// ----------------------------------------------------------------------------
// 'SDeltaPtCutStudyLinkDef.h'
// Derek Anderson
// 08.11.2023
//
// Reads in the 'ntp_track' Ntuple
// generated by the SVtxEvaluator
// class and studies how deltapt/pt
// varies with quality cuts.
// ----------------------------------------------------------------------------

#ifdef __CINT__

#pragma link C++ class SDeltaPtCutStudy-!;

#endif

// end ------------------------------------------------------------------------
