# -----------------------------------------------------------------------------
# 'RunStandaloneCorrelatorCalculationOnCondor.job'
# Derek Anderson
# 03.20.2024
#
# Job file to run standalone correlator calculations via condor.
# -----------------------------------------------------------------------------

# generic parameters
Universe     = vanilla
notification = Never

# executable parameters
Executable           = DoStandaloneCorrelatorCalculationOnCondor.sh
Initialdir           = ./
request_memory       = 8GB
transfer_input_files = DoStandaloneCorrelatorCalculation.cxx,EnergyCorrelatorOptions.h

# output parameters
Output = /sphenix/user/danderson/eec/SEnergyCorrelator/log/testCalc.out
Error  = /sphenix/user/danderson/eec/SEnergyCorrelator/log/testCalc.err
Log    = /sphenix/user/danderson/eec/SEnergyCorrelator/log/testCalc.log

# queue jobs
Queue

# end -------------------------------------------------------------------------
