#! /usr/bin/env python
from optparse import OptionParser
import sys
import os
import datetime
from array import *
from ROOT import TH1F, TH2F, kRainBow, kBird, kHAlignRight, kVAlignBottom, kHAlignLeft, kVAlignTop, kThermometer, gROOT, gStyle
import numpy
import math
import glob
from plotUtil import *

# gROOT.LoadMacro('./sPHENIXStyle/sPhenixStyle.C')
# gROOT.ProcessLine('SetsPhenixStyle()')
gROOT.SetBatch(True)

if __name__ == '__main__':
    parser = OptionParser()
    parser.add_option("-f", "--histdir", dest="histdir", type="string", default='/sphenix/user/hjheng/TrackletAna/analysis_INTT/plot/hists/data_Run20869/Cluster', help="Input file name")
    parser.add_option("-d", "--plotdir", dest="plotdir", type="string", default='/sphenix/user/hjheng/TrackletAna/analysis_INTT/plot/RecoCluster/data_Run20869', help="Plot directory")
    parser.add_option("-s", "--isdata", dest="isdata", action="store_true", default=False, help="Is data")
    parser.add_option("-p", "--preliminary", dest="preliminary", action="store_true", default=False, help="Preliminary")
    (opt, args) = parser.parse_args()
    print('opt: {}'.format(opt))

    histdir = opt.histdir
    plotdir = opt.plotdir
    isdata = opt.isdata
    preliminary = opt.preliminary
    os.makedirs(plotdir, exist_ok=True)

    if os.path.isfile("{}/hists_merged.root".format(histdir)):
        # os.system("rm {}/hists_merged.root".format(histdir))
        os.system("hadd -f -j 20 {}/hists_merged.root {}/hists_*.root".format(histdir, histdir))
    else:
        os.system("hadd -f -j 20 {}/hists_merged.root {}/hists_*.root".format(histdir, histdir))

    hM_ClusZ_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZ_all')
    hM_ClusZ_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZ_layer1')
    hM_ClusZ_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZ_layer2')
    hM_ClusEtaPV_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_all')
    hM_ClusEtaPV_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_layer1')
    hM_ClusEtaPV_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_layer2')
    hM_ClusEtaPV_all_ClusADCg35 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_all_ClusADCg35')
    hM_ClusEtaPV_layer1_ClusADCg35 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_layer1_ClusADCg35')
    hM_ClusEtaPV_layer2_ClusADCg35 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_layer2_ClusADCg35')
    hM_ClusEtaPV_all_weiClusADCoverPhiSize = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_all_weiClusADCoverPhiSize')
    hM_ClusEtaPV_layer1_weiClusADCoverPhiSize = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_layer1_weiClusADCoverPhiSize')
    hM_ClusEtaPV_layer2_weiClusADCoverPhiSize = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_layer2_weiClusADCoverPhiSize')
    hM_ClusEtaPV_all_ClusADCg35_weiClusADCoverPhiSize = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_all_ClusADCg35_weiClusADCoverPhiSize')
    hM_ClusEtaPV_layer1_ClusADCg35_weiClusADCoverPhiSize = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_layer1_ClusADCg35_weiClusADCoverPhiSize')
    hM_ClusEtaPV_layer2_ClusADCg35_weiClusADCoverPhiSize = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_layer2_ClusADCg35_weiClusADCoverPhiSize')
    hM_ClusPhiPV_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiPV_all')
    hM_ClusPhiPV_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiPV_layer1')
    hM_ClusPhiPV_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiPV_layer2')
    hM_ClusPhiPV_ClusPhiSize43or46 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiPV_ClusPhiSize43or46')
    hM_ClusADC_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusADC_all')
    hM_ClusADC_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusADC_layer1')
    hM_ClusADC_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusADC_layer2')
    # hM_ClusZSize_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZSize_all')
    # hM_ClusZSize_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZSize_layer1')
    # hM_ClusZSize_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZSize_layer2')
    hM_ClusPhiSize_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiSize_all')
    hM_ClusPhiSize_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiSize_layer1')
    hM_ClusPhiSize_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiSize_layer2')

    hM_ClusX_ClusY_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusX_ClusY_all')
    hM_ClusX_ClusY_ClusPhiSize43or46 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusX_ClusY_ClusPhiSize43or46')
    hM_ClusX_ClusY_ClusPhiSize43 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusX_ClusY_ClusPhiSize43')
    hM_ClusX_ClusY_ClusPhiSize46 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusX_ClusY_ClusPhiSize46')
    hM_ClusX_ClusY_all_weiphisize = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusX_ClusY_all_weiphisize')
    hM_ClusX_ClusY_all_weiclusadc = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusX_ClusY_all_weiclusadc')
    hM_ClusZ_ClusPhiPV_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZ_ClusPhiPV_all')
    hM_ClusZ_ClusPhiPV_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZ_ClusPhiPV_layer1')
    hM_ClusZ_ClusPhiPV_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZ_ClusPhiPV_layer2')
    hM_ClusZ_ClusPhiPV_all_coarse = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZ_ClusPhiPV_all_coarse')
    hM_ClusZ_ClusPhiPV_all_coarse_weiphisize = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZ_ClusPhiPV_all_coarse_weiphisize')
    hM_ClusZ_ClusPhiPV_all_coarse_weiclusadc = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZ_ClusPhiPV_all_coarse_weiclusadc')
    # hM_ClusEtaPV_ClusZSize_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusZSize_all')
    # hM_ClusEtaPV_ClusZSize_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusZSize_layer1')
    # hM_ClusEtaPV_ClusZSize_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusZSize_layer2')
    hM_ClusPhiPV_ClusPhiSize_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiPV_ClusPhiSize_all')
    hM_ClusPhiPV_ClusPhiSize_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiPV_ClusPhiSize_layer1')
    hM_ClusPhiPV_ClusPhiSize_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiPV_ClusPhiSize_layer2')
    hM_ClusEtaPV_ClusADC_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADC_all')
    hM_ClusEtaPV_ClusADC_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADC_layer1')
    hM_ClusEtaPV_ClusADC_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADC_layer2')
    hM_ClusEtaPV_ClusADC_all_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADC_all_zoomin')
    hM_ClusEtaPV_ClusADC_layer1_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADC_layer1_zoomin')
    hM_ClusEtaPV_ClusADC_layer2_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADC_layer2_zoomin')
    hM_ClusEtaPV_ClusPhiSize_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusPhiSize_all')
    hM_ClusEtaPV_ClusPhiSize_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusPhiSize_layer1')
    hM_ClusEtaPV_ClusPhiSize_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusPhiSize_layer2')
    hM_ClusEtaPV_ClusPhiSize_all_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusPhiSize_all_zoomin')
    hM_ClusEtaPV_ClusPhiSize_layer1_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusPhiSize_layer1_zoomin')
    hM_ClusEtaPV_ClusPhiSize_layer2_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusPhiSize_layer2_zoomin')
    hM_ClusPhiPV_ClusADC_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiPV_ClusADC_all')
    hM_ClusPhiPV_ClusADC_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiPV_ClusADC_layer1')
    hM_ClusPhiPV_ClusADC_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiPV_ClusADC_layer2')
    # hM_ClusZSize_ClusPhiSize_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZSize_ClusPhiSize_all')
    # hM_ClusZSize_ClusPhiSize_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZSize_ClusPhiSize_layer1')
    # hM_ClusZSize_ClusPhiSize_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZSize_ClusPhiSize_layer2')
    # hM_ClusZSize_ClusADC_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZSize_ClusADC_all')
    # hM_ClusZSize_ClusADC_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZSize_ClusADC_layer1')
    # hM_ClusZSize_ClusADC_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusZSize_ClusADC_layer2')
    hM_ClusPhiSize_ClusADC_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiSize_ClusADC_all')
    hM_ClusPhiSize_ClusADC_layer1 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiSize_ClusADC_layer1')
    hM_ClusPhiSize_ClusADC_layer2 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiSize_ClusADC_layer2')
    hM_ClusPhiSize_ClusADC_all_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiSize_ClusADC_all_zoomin')
    hM_ClusPhiSize_ClusADC_layer1_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiSize_ClusADC_layer1_zoomin')
    hM_ClusPhiSize_ClusADC_layer2_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusPhiSize_ClusADC_layer2_zoomin')
    hM_ClusEtaPV_ClusADCoverClusPhiSize_all_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADCoverClusPhiSize_all_zoomin')
    hM_ClusEtaPV_ClusADCoverClusPhiSize_layer1_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADCoverClusPhiSize_layer1_zoomin')
    hM_ClusEtaPV_ClusADCoverClusPhiSize_layer2_zoomin = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADCoverClusPhiSize_layer2_zoomin')
    hM_ClusEtaPV_ClusADCoverClusPhiSize_all_ClusADCg35 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADCoverClusPhiSize_all_ClusADCg35')
    hM_ClusEtaPV_ClusADCoverClusPhiSize_layer1_ClusADCg35 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADCoverClusPhiSize_layer1_ClusADCg35')
    hM_ClusEtaPV_ClusADCoverClusPhiSize_layer2_ClusADCg35 = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_ClusEtaPV_ClusADCoverClusPhiSize_layer2_ClusADCg35')
    
    hM_mutualdRcluster_all = GetHistogram('{}/hists_merged.root'.format(histdir), 'hM_mutualdRcluster_all')
    
    # Draw_1Dhist(hist, IsData, norm1, logy, ymaxscale, XaxisName, Ytitle_unit, outname)
    Draw_1Dhist(hM_ClusZ_all, isdata, False, False, 1.3, 'Cluster Z [cm]', 'cm', '{}/ClusZ_all'.format(plotdir))
    Draw_1Dhist(hM_ClusZ_layer1, isdata, False, False, 1.3, 'Cluster Z [cm]', 'cm', '{}/ClusZ_layer1'.format(plotdir))
    Draw_1Dhist(hM_ClusZ_layer2, isdata, False, False, 1.3, 'Cluster Z [cm]', 'cm', '{}/ClusZ_layer2'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_all, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_all'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer1, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer1'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer2, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer2'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_all_ClusADCg35, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_all_ClusADCg35'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer1_ClusADCg35, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer1_ClusADCg35'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer2_ClusADCg35, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer2_ClusADCg35'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_all_weiClusADCoverPhiSize, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_all_weiClusADCoverPhiSize'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer1_weiClusADCoverPhiSize, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer1_weiClusADCoverPhiSize'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer2_weiClusADCoverPhiSize, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer2_weiClusADCoverPhiSize'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_all_ClusADCg35_weiClusADCoverPhiSize, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_all_ClusADCg35_weiClusADCoverPhiSize'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer1_ClusADCg35_weiClusADCoverPhiSize, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer1_ClusADCg35_weiClusADCoverPhiSize'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer2_ClusADCg35_weiClusADCoverPhiSize, isdata, False, False, 1.3, 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer2_ClusADCg35_weiClusADCoverPhiSize'.format(plotdir))
    Draw_1Dhist(hM_ClusPhiPV_all, isdata, False, False, 1.3, 'Cluster #phi (w.r.t PV)', '', '{}/ClusPhiPV_all'.format(plotdir))
    Draw_1Dhist(hM_ClusPhiPV_layer1, isdata, False, False, 1.3, 'Cluster #phi (w.r.t PV)', '', '{}/ClusPhiPV_layer1'.format(plotdir))
    Draw_1Dhist(hM_ClusPhiPV_layer2, isdata, False, False, 1.3, 'Cluster #phi (w.r.t PV)', '', '{}/ClusPhiPV_layer2'.format(plotdir))
    Draw_1Dhist(hM_ClusPhiPV_ClusPhiSize43or46, isdata, False, False, 1.3, 'Cluster #phi (w.r.t PV)', '', '{}/ClusPhiPV_ClusPhiSize43or46'.format(plotdir))
    Draw_1Dhist(hM_ClusADC_all, isdata, False, True, 100, 'Cluster ADC', '', '{}/ClusADC_all'.format(plotdir))
    Draw_1Dhist(hM_ClusADC_layer1, isdata, False, True, 100, 'Cluster ADC', '', '{}/ClusADC_layer1'.format(plotdir))
    Draw_1Dhist(hM_ClusADC_layer2, isdata, False, True, 100, 'Cluster ADC', '', '{}/ClusADC_layer2'.format(plotdir))
    # Draw_1Dhist(hM_ClusZSize_all, isdata, False, True, 100, 'Cluster Z size', '', '{}/ClusZSize_all'.format(plotdir))
    # Draw_1Dhist(hM_ClusZSize_layer1, isdata, False, True, 100, 'Cluster Z size', '', '{}/ClusZSize_layer1'.format(plotdir))
    # Draw_1Dhist(hM_ClusZSize_layer2, isdata, False, True, 100, 'Cluster Z size', '', '{}/ClusZSize_layer2'.format(plotdir))
    Draw_1Dhist(hM_ClusPhiSize_all, isdata, False, True, 100, 'Cluster #phi size', '', '{}/ClusPhiSize_all'.format(plotdir))
    Draw_1Dhist(hM_ClusPhiSize_layer1, isdata, False, True, 100, 'Cluster #phi size', '', '{}/ClusPhiSize_layer1'.format(plotdir))
    Draw_1Dhist(hM_ClusPhiSize_layer2, isdata, False, True, 100, 'Cluster #phi size', '', '{}/ClusPhiSize_layer2'.format(plotdir))
    hM_ClusEtaPV_all_avgclusadcoverphisize = hM_ClusEtaPV_all_weiClusADCoverPhiSize.Clone('hM_ClusEtaPV_all_avgclusadcoverphisize')
    hM_ClusEtaPV_layer1_avgclusadcoverphisize = hM_ClusEtaPV_layer1_weiClusADCoverPhiSize.Clone('hM_ClusEtaPV_layer1_avgclusadcoverphisize')
    hM_ClusEtaPV_layer2_avgclusadcoverphisize = hM_ClusEtaPV_layer2_weiClusADCoverPhiSize.Clone('hM_ClusEtaPV_layer2_avgclusadcoverphisize')
    hM_ClusEtaPV_all_avgclusadcoverphisize.Divide(hM_ClusEtaPV_all)
    hM_ClusEtaPV_layer1_avgclusadcoverphisize.Divide(hM_ClusEtaPV_layer1)
    hM_ClusEtaPV_layer2_avgclusadcoverphisize.Divide(hM_ClusEtaPV_layer2)
    print (hM_ClusEtaPV_all_avgclusadcoverphisize.GetBinContent(hM_ClusEtaPV_all_avgclusadcoverphisize.GetMaximumBin()))
    # reset the histogram range
    hM_ClusEtaPV_all_avgclusadcoverphisize.GetYaxis().SetRangeUser(0, hM_ClusEtaPV_all_avgclusadcoverphisize.GetBinContent(hM_ClusEtaPV_all_avgclusadcoverphisize.GetMaximumBin())*1.3)
    hM_ClusEtaPV_layer1_avgclusadcoverphisize.GetYaxis().SetRangeUser(0, hM_ClusEtaPV_layer1_avgclusadcoverphisize.GetBinContent(hM_ClusEtaPV_layer1_avgclusadcoverphisize.GetMaximumBin())*1.3)
    hM_ClusEtaPV_layer2_avgclusadcoverphisize.GetYaxis().SetRangeUser(0, hM_ClusEtaPV_layer2_avgclusadcoverphisize.GetBinContent(hM_ClusEtaPV_layer2_avgclusadcoverphisize.GetMaximumBin())*1.3)
    Draw_1Dhist(hM_ClusEtaPV_all_avgclusadcoverphisize, isdata, False, False, 1., 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_all_avgclusadcoverphisize'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer1_avgclusadcoverphisize, isdata, False, False, 1., 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer1_avgclusadcoverphisize'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer2_avgclusadcoverphisize, isdata, False, False, 1., 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer2_avgclusadcoverphisize'.format(plotdir))
    hM_ClusEtaPV_all_ClusADCg35_avgclusadcoverphisize = hM_ClusEtaPV_all_ClusADCg35_weiClusADCoverPhiSize.Clone('hM_ClusEtaPV_all_ClusADCg35_avgclusadcoverphisize')
    hM_ClusEtaPV_layer1_ClusADCg35_avgclusadcoverphisize = hM_ClusEtaPV_layer1_ClusADCg35_weiClusADCoverPhiSize.Clone('hM_ClusEtaPV_layer1_ClusADCg35_avgclusadcoverphisize')
    hM_ClusEtaPV_layer2_ClusADCg35_avgclusadcoverphisize = hM_ClusEtaPV_layer2_ClusADCg35_weiClusADCoverPhiSize.Clone('hM_ClusEtaPV_layer2_ClusADCg35_avgclusadcoverphisize')
    hM_ClusEtaPV_all_ClusADCg35_avgclusadcoverphisize.Divide(hM_ClusEtaPV_all_ClusADCg35)
    hM_ClusEtaPV_layer1_ClusADCg35_avgclusadcoverphisize.Divide(hM_ClusEtaPV_layer1_ClusADCg35)
    hM_ClusEtaPV_layer2_ClusADCg35_avgclusadcoverphisize.Divide(hM_ClusEtaPV_layer2_ClusADCg35)
    hM_ClusEtaPV_all_ClusADCg35_avgclusadcoverphisize.GetYaxis().SetRangeUser(0, hM_ClusEtaPV_all_ClusADCg35_avgclusadcoverphisize.GetBinContent(hM_ClusEtaPV_all_ClusADCg35_avgclusadcoverphisize.GetMaximumBin())*1.3)
    hM_ClusEtaPV_layer1_ClusADCg35_avgclusadcoverphisize.GetYaxis().SetRangeUser(0, hM_ClusEtaPV_layer1_ClusADCg35_avgclusadcoverphisize.GetBinContent(hM_ClusEtaPV_layer1_ClusADCg35_avgclusadcoverphisize.GetMaximumBin())*1.3)
    hM_ClusEtaPV_layer2_ClusADCg35_avgclusadcoverphisize.GetYaxis().SetRangeUser(0, hM_ClusEtaPV_layer2_ClusADCg35_avgclusadcoverphisize.GetBinContent(hM_ClusEtaPV_layer2_ClusADCg35_avgclusadcoverphisize.GetMaximumBin())*1.3)
    Draw_1Dhist(hM_ClusEtaPV_all_ClusADCg35_avgclusadcoverphisize, isdata, False, False, 1., 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_all_ClusADCg35_avgclusadcoverphisize'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer1_ClusADCg35_avgclusadcoverphisize, isdata, False, False, 1., 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer1_ClusADCg35_avgclusadcoverphisize'.format(plotdir))
    Draw_1Dhist(hM_ClusEtaPV_layer2_ClusADCg35_avgclusadcoverphisize, isdata, False, False, 1., 'Cluster #eta (w.r.t PV)', '', '{}/ClusEtaPV_layer2_ClusADCg35_avgclusadcoverphisize'.format(plotdir))
    
    Draw_1Dhist(hM_mutualdRcluster_all, isdata, False, False, 1.3, 'dR(cluster, cluster)', '', '{}/mutualdRcluster_all'.format(plotdir))

    # Draw_2Dhist(hist, IsData, logz, norm1, rmargin, XaxisName, YaxisName, drawopt, outname)
    gStyle.SetPalette(kBird)
    # gStyle.SetPalette(kRainBow)
    Draw_2Dhist(hM_ClusX_ClusY_all, isdata, False, False, 0.15, 'Cluster X [cm]', 'Cluster Y [cm]', 'Entries', 'colz', '{}/ClusX_ClusY_all'.format(plotdir))
    Draw_2Dhist(hM_ClusX_ClusY_ClusPhiSize43or46, isdata, True, False, 0.15, 'Cluster X [cm]', 'Cluster Y [cm]', 'Entries', 'colz', '{}/ClusX_ClusY_ClusPhiSize43or46'.format(plotdir))
    Draw_2Dhist(hM_ClusX_ClusY_ClusPhiSize43, isdata, True, False, 0.15, 'Cluster X [cm]', 'Cluster Y [cm]', 'Entries', 'colz', '{}/ClusX_ClusY_ClusPhiSize43'.format(plotdir))
    Draw_2Dhist(hM_ClusX_ClusY_ClusPhiSize46, isdata, True, False, 0.15, 'Cluster X [cm]', 'Cluster Y [cm]', 'Entries', 'colz', '{}/ClusX_ClusY_ClusPhiSize46'.format(plotdir))
    Draw_2Dhist(hM_ClusX_ClusY_all_weiphisize, isdata, False, False, 0.15, 'Cluster X [cm]', 'Cluster Y [cm]','Entries', 'colz', '{}/ClusX_ClusY_all_weiphisize'.format(plotdir))
    hM_ClusX_ClusY_all_avgphisize = hM_ClusX_ClusY_all_weiphisize.Clone('hM_ClusX_ClusY_all_avgphisize')
    hM_ClusX_ClusY_all_avgclusadc = hM_ClusX_ClusY_all_weiclusadc.Clone('hM_ClusX_ClusY_all_avgclusadc')
    hM_ClusX_ClusY_all_avgphisize.Divide(hM_ClusX_ClusY_all)
    hM_ClusX_ClusY_all_avgclusadc.Divide(hM_ClusX_ClusY_all)
    Draw_2Dhist(hM_ClusX_ClusY_all_avgphisize, isdata, False, False, 0.15, 'Cluster X [cm]', 'Cluster Y [cm]','Average cluster #phi size', 'colz', '{}/ClusX_ClusY_all_avgphisize'.format(plotdir))
    Draw_2Dhist(hM_ClusX_ClusY_all_avgclusadc, isdata, False, False, 0.15, 'Cluster X [cm]', 'Cluster Y [cm]', 'Average cluster ADC', 'colz', '{}/ClusX_ClusY_all_avgclusadc'.format(plotdir))

    Draw_2Dhist(hM_ClusZ_ClusPhiPV_all, isdata, False, False, 0.16, 'Cluster Z [cm]', 'Cluster #phi (w.r.t PV)', 'Entries', 'colz', '{}/ClusZ_ClusPhiPV_all'.format(plotdir))
    Draw_2Dhist(hM_ClusZ_ClusPhiPV_layer1, isdata, False, False, 0.16, 'Cluster Z [cm]', 'Cluster #phi (w.r.t PV)', 'Entries', 'colz', '{}/ClusZ_ClusPhiPV_layer1'.format(plotdir))
    Draw_2Dhist(hM_ClusZ_ClusPhiPV_layer2, isdata, False, False, 0.16, 'Cluster Z [cm]', 'Cluster #phi (w.r.t PV)', 'Entries', 'colz', '{}/ClusZ_ClusPhiPV_layer2'.format(plotdir))
    Draw_2Dhist(hM_ClusZ_ClusPhiPV_all_coarse, isdata, False, False, 0.16, 'Cluster Z [cm]', 'Cluster #phi (w.r.t PV)', 'Entries', 'colz', '{}/ClusZ_ClusPhiPV_all_coarse'.format(plotdir))
    hM_ClusZ_ClusPhiPV_all_coarse_avgphisize = hM_ClusZ_ClusPhiPV_all_coarse_weiphisize.Clone('hM_ClusZ_ClusPhiPV_all_coarse_avgphisize')
    hM_ClusZ_ClusPhiPV_all_coarse_avgclusadc = hM_ClusZ_ClusPhiPV_all_coarse_weiclusadc.Clone('hM_ClusZ_ClusPhiPV_all_coarse_avgclusadc')
    hM_ClusZ_ClusPhiPV_all_coarse_avgphisize.Divide(hM_ClusZ_ClusPhiPV_all_coarse)
    hM_ClusZ_ClusPhiPV_all_coarse_avgclusadc.Divide(hM_ClusZ_ClusPhiPV_all_coarse)
    Draw_2Dhist(hM_ClusZ_ClusPhiPV_all_coarse_avgphisize, isdata, False, False, 0.16, 'Cluster Z [cm]', 'Cluster #phi (w.r.t PV)', 'Average cluster #phi size', 'colz', '{}/ClusZ_ClusPhiPV_all_coarse_avgphisize'.format(plotdir))
    Draw_2Dhist(hM_ClusZ_ClusPhiPV_all_coarse_avgclusadc, isdata, False, False, 0.16, 'Cluster Z [cm]', 'Cluster #phi (w.r.t PV)', 'Average cluster ADC', 'colz', '{}/ClusZ_ClusPhiPV_all_coarse_avgclusadc'.format(plotdir))
    # Draw_2Dhist(hM_ClusEtaPV_ClusZSize_all, isdata, True, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster Z size', 'colz', '{}/ClusEtaPV_ClusZSize_all'.format(plotdir))
    # Draw_2Dhist(hM_ClusEtaPV_ClusZSize_layer1, isdata, True, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster Z size', 'colz', '{}/ClusEtaPV_ClusZSize_layer1'.format(plotdir))
    # Draw_2Dhist(hM_ClusEtaPV_ClusZSize_layer2, isdata, True, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster Z size', 'colz', '{}/ClusEtaPV_ClusZSize_layer2'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiPV_ClusPhiSize_all, isdata, False, False, 0.16, 'Cluster #phi (w.r.t PV)', 'Cluster #phi size', 'Entries', 'colz', '{}/ClusPhiPV_ClusPhiSize_all'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiPV_ClusPhiSize_layer1, isdata, False, False, 0.16, 'Cluster #phi (w.r.t PV)', 'Cluster #phi size', 'Entries', 'colz', '{}/ClusPhiPV_ClusPhiSize_layer1'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiPV_ClusPhiSize_layer2, isdata, False, False, 0.16, 'Cluster #phi (w.r.t PV)', 'Cluster #phi size', 'Entries', 'colz', '{}/ClusPhiPV_ClusPhiSize_layer2'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADC_all, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC', 'Entries', 'colz', '{}/ClusEtaPV_ClusADC_all'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADC_layer1, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC', 'Entries', 'colz', '{}/ClusEtaPV_ClusADC_layer1'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADC_layer2, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC', 'Entries', 'colz', '{}/ClusEtaPV_ClusADC_layer2'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADC_all_zoomin, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC', 'Entries', 'colz', '{}/ClusEtaPV_ClusADC_all_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADC_layer1_zoomin, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC', 'Entries', 'colz', '{}/ClusEtaPV_ClusADC_layer1_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADC_layer2_zoomin, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC', 'Entries', 'colz', '{}/ClusEtaPV_ClusADC_layer2_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusPhiSize_all, isdata, True, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusPhiSize_all'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusPhiSize_layer1, isdata, True, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusPhiSize_layer1'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusPhiSize_layer2, isdata, True, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusPhiSize_layer2'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusPhiSize_all_zoomin, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusPhiSize_all_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusPhiSize_layer1_zoomin, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusPhiSize_layer1_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusPhiSize_layer2_zoomin, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusPhiSize_layer2_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiPV_ClusADC_all, isdata, False, False, 0.16, 'Cluster #phi (w.r.t PV)', 'Cluster ADC', 'Entries', 'colz', '{}/ClusPhiPV_ClusADC_all'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiPV_ClusADC_layer1, isdata, False, False, 0.16, 'Cluster #phi (w.r.t PV)', 'Cluster ADC', 'Entries', 'colz', '{}/ClusPhiPV_ClusADC_layer1'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiPV_ClusADC_layer2, isdata, False, False, 0.16, 'Cluster #phi (w.r.t PV)', 'Cluster ADC', 'Entries', 'colz', '{}/ClusPhiPV_ClusADC_layer2'.format(plotdir))
    # Draw_2Dhist(hM_ClusZSize_ClusPhiSize_all, isdata, True, False, 0.16, 'Cluster Z size', 'Cluster #phi size', 'colz', '{}/ClusZSize_ClusPhiSize_all'.format(plotdir))
    # Draw_2Dhist(hM_ClusZSize_ClusPhiSize_layer1, isdata, True, False, 0.16, 'Cluster Z size', 'Cluster #phi size', 'colz', '{}/ClusZSize_ClusPhiSize_layer1'.format(plotdir))
    # Draw_2Dhist(hM_ClusZSize_ClusPhiSize_layer2, isdata, True, False, 0.16, 'Cluster Z size', 'Cluster #phi size', 'colz', '{}/ClusZSize_ClusPhiSize_layer2'.format(plotdir))
    # Draw_2Dhist(hM_ClusZSize_ClusADC_all, isdata, True, False, 0.16, 'Cluster Z size', 'Cluster #phi size', 'colz', '{}/ClusZSize_ClusADC_all'.format(plotdir))
    # Draw_2Dhist(hM_ClusZSize_ClusADC_layer1, isdata, True, False, 0.16, 'Cluster Z size', 'Cluster ADC', 'colz', '{}/ClusZSize_ClusADC_layer1'.format(plotdir))
    # Draw_2Dhist(hM_ClusZSize_ClusADC_layer2, isdata, True, False, 0.16, 'Cluster Z size', 'Cluster ADC', 'colz', '{}/ClusZSize_ClusADC_layer2'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiSize_ClusADC_all, isdata, True, False, 0.16, 'Cluster #phi size', 'Cluster ADC', 'Entries', 'colz', '{}/ClusPhiSize_ClusADC_all'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiSize_ClusADC_layer1, isdata, True, False, 0.16, 'Cluster #phi size', 'Cluster ADC', 'Entries', 'colz', '{}/ClusPhiSize_ClusADC_layer1'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiSize_ClusADC_layer2, isdata, True, False, 0.16, 'Cluster #phi size', 'Cluster ADC', 'Entries', 'colz', '{}/ClusPhiSize_ClusADC_layer2'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiSize_ClusADC_all_zoomin, isdata, False, False, 0.16, 'Cluster #phi size', 'Cluster ADC', 'Entries', 'colz', '{}/ClusPhiSize_ClusADC_all_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiSize_ClusADC_layer1_zoomin, isdata, False, False, 0.16, 'Cluster #phi size', 'Cluster ADC', 'Entries', 'colz', '{}/ClusPhiSize_ClusADC_layer1_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusPhiSize_ClusADC_layer2_zoomin, isdata, False, False, 0.16, 'Cluster #phi size', 'Cluster ADC', 'Entries', 'colz', '{}/ClusPhiSize_ClusADC_layer2_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADCoverClusPhiSize_all_zoomin, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC/Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusADCoverClusPhiSize_all_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADCoverClusPhiSize_layer1_zoomin, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC/Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusADCoverClusPhiSize_layer1_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADCoverClusPhiSize_layer2_zoomin, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC/Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusADCoverClusPhiSize_layer2_zoomin'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADCoverClusPhiSize_all_ClusADCg35, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC/Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusADCoverClusPhiSize_all_ClusADCg35'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADCoverClusPhiSize_layer1_ClusADCg35, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC/Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusADCoverClusPhiSize_layer1_ClusADCg35'.format(plotdir))
    Draw_2Dhist(hM_ClusEtaPV_ClusADCoverClusPhiSize_layer2_ClusADCg35, isdata, False, False, 0.16, 'Cluster #eta (w.r.t PV)', 'Cluster ADC/Cluster #phi size', 'Entries', 'colz', '{}/ClusEtaPV_ClusADCoverClusPhiSize_layer2_ClusADCg35'.format(plotdir))