Universe 	        = vanilla 
Executable 	= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/LargeRLCaloENC/macros/RunLargeRLENC.sh 
Arguments         = DST_CALO_run2pp_ana462_2024p010_v001-00053880-00116.root DST_CALOFITTING_run2pp_ana462_2024p010_v001-00053880-00122.root DST_TRIGGERED_EVENT_run2pp_ana462_nocdbtag_v001-00053880-00118.root DST_JET_run2pp_ana462_2024p010_v001-00053880-00116.root none none none none 0 
Output  	        = /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/LargeRLCaloENC/macros/condor_files/data_condor_53880_116.out 
Error 		= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/LargeRLCaloENC/macros/condor_files/data_condor_53880_116.err 
Log  		= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/LargeRLCaloENC/macros/condor_files/data_condor_53880_116.log
Initialdir  	= /gpfs/mnt/gpfs02/sphenix/user/sgross/sphenix_analysis/EnergyCorrelatorsJets/LargeRLCaloENC/root_output_threshold_scan
PeriodicHold 	= (NumJobStarts>=1 && JobStatus == 1)
accounting_group = group_phenix.u 
accounting_group_user = sgross 
request_memory = 128192MB 
Priority = 90 
job_lease_duration = 3600
Queue 1
