Universe           = vanilla
Initialdir         = /sphenix/user/ChengWei/INTT/INTT_dNdeta_repo/DST_MC/control_files/GeoUncStudy/evt_tracklet/condor_outputs
Executable         = /sphenix/user/ChengWei/INTT/INTT_dNdeta_repo/DST_MC/control_files/GeoUncStudy/evt_tracklet/run_root_sub_evtTracklet_the_file_number.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 4GB
Priority           = 20
job_lease_duration = 172800
nEvents            = NEVENTS
InputfilelistIdx   = INPUTFILELISTIDX
FileName           = FILENAME
skipEvt            = 0
Output             = /sphenix/user/ChengWei/sPH_dNdeta/Sim_Ntuple_HIJING_new_20240424_HR_test/Geo_test/evt_tracklet/CW_log/condor_output_the_file_number.out
Error              = /sphenix/user/ChengWei/sPH_dNdeta/Sim_Ntuple_HIJING_new_20240424_HR_test/Geo_test/evt_tracklet/CW_log/condor_output_the_file_number.err
Log                = /sphenix/user/ChengWei/sPH_dNdeta/Sim_Ntuple_HIJING_new_20240424_HR_test/Geo_test/evt_tracklet/CW_log/condor_output_the_file_number.log
Arguments          = "$(nEvents) $(InputfilelistIdx) $(FileName) $(skipEvt)"
Queue 1

