/********************************************************************
* JetPerformance_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error JetPerformance_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJetPerformance_Dict();
extern void G__cpp_setup_inheritanceJetPerformance_Dict();
extern void G__cpp_setup_typetableJetPerformance_Dict();
extern void G__cpp_setup_memvarJetPerformance_Dict();
extern void G__cpp_setup_globalJetPerformance_Dict();
extern void G__cpp_setup_memfuncJetPerformance_Dict();
extern void G__cpp_setup_funcJetPerformance_Dict();
extern void G__set_cpp_environmentJetPerformance_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JetPerformance.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JetPerformance_DictLN_string;
extern G__linked_taginfo G__JetPerformance_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JetPerformance_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JetPerformance_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JetPerformance_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JetPerformance_DictLN_Fun4AllBase;
extern G__linked_taginfo G__JetPerformance_DictLN_PHCompositeNode;
extern G__linked_taginfo G__JetPerformance_DictLN_SubsysReco;
extern G__linked_taginfo G__JetPerformance_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__JetPerformance_DictLN_TTree;
extern G__linked_taginfo G__JetPerformance_DictLN_TFile;
extern G__linked_taginfo G__JetPerformance_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__JetPerformance_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__JetPerformance_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__JetPerformance_DictLN_TH1F;
extern G__linked_taginfo G__JetPerformance_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__JetPerformance_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__JetPerformance_DictLN_JetPerformance;

/* STUB derived class for protected member access */
