Universe	= vanilla
Executable	= runHerwigUE.sh
notification	= Never
Output		= /sphenix/user/bkimelman/logs/HerwigUE/HerwigUE_$(Sample)_$(seg)_$(clusterId).$(process).txt
Error		= /sphenix/user/bkimelman/logs/HerwigUE/HerwigUE_$(Sample)_$(seg)_$(clusterId).$(process).err
Log		= /tmp/condor_bkimelman_$(clusterId).$(process).log
Initialdir	= /sphenix/u/bkimelman/analysis/HERWIG_UE/
Arguments	= $(Sample) $(seg)
request_memory	= 5000MB
PeriodicHold = (NumJobStarts>=1 && JobStatus == 1)
Queue Sample, seg from HERWIG_samples_20.list
