Universe           = vanilla
initialDir         = . 
Executable         = $(initialDir)/run_geometric_acceptance.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 8GB
Priority           = 20
job_lease_duration = 3600
logHeader          = /tmp/log_mjpeters/geometric_acceptance_$INT(Process,%06d)
outHeader          = $(initialDir)/log/geometric_acceptance_$INT(Process,%06d)
Output             = $(outHeader).out
Error              = $(outHeader).err
Log                = $(logHeader).log
Arguments          = $INT(Process,%06d) 
Queue 10000
