executable = InclusiveJet.sh
arguments = 0 $(Process) 1 runlist2.txt run22_herwig_jet30
output = output_logs/mc_herwig_jet30_output_$(Process).out
request_memory = 4GB
when_to_transfer_output = ON_EXIT
error			= output_logs/mc_herwig_jet30_error_$(Process).err
log = /tmp/egm2153_$(Process).log
PeriodicHold = (NumJobStarts>=1 && JobStatus == 1)
concurrency_limits=CONCURRENCY_LIMIT_DEFAULT:100
queue 3334
