Universe           = vanilla
initialDir         = . 
#Executable         = $(initialDir)/runSkimmer.sh
Executable         = $(initialDir)/runKS0Skimmer.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 10GB
Priority           = 20
job_lease_duration = 3600
logHeader          = $(initialDir)/condor_KS0skimmer_$INT(Process,%05d)
Output             = $(logHeader).out
Error              = $(logHeader).err
Log                = $(logHeader).log
Queue 1
