Universe           = vanilla
Initialdir         = /sphenix/user/ChengWei/INTT/INTT_dNdeta_repo/DST_MC/control_files/full_control_script/for_data/evt_vtxZ
Executable         = run_root_mother.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400
# nEvents            = NEVENTS
# InputfilelistIdx   = INPUTFILELISTIDX
# FileName           = FILENAME
# skipEvt            = 0
data_type          = data
control_file       = /sphenix/user/ChengWei/INTT/INTT_dNdeta_repo/DST_MC/control_files/full_control_script/for_data/evt_vtxZ
output_sub_folder  = evt_vtxZ_trapezoidal
used_zvtx_folder   = evt_vtxZ
Output             = /sphenix/user/ChengWei/INTT/INTT_commissioning/ZeroField/F4A_20869/2024_05_07/folder_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey_test/evt_vtxZ_trapezoidal/CW_log/condor_$(process).out
Error              = /sphenix/user/ChengWei/INTT/INTT_commissioning/ZeroField/F4A_20869/2024_05_07/folder_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey_test/evt_vtxZ_trapezoidal/CW_log/condor_$(process).err
Log                = /sphenix/user/ChengWei/INTT/INTT_commissioning/ZeroField/F4A_20869/2024_05_07/folder_Data_CombinedNtuple_Run20869_HotDead_BCO_ADC_Survey_test/evt_vtxZ_trapezoidal/CW_log/condor_$(process).log
Arguments          = "$(data_type) $(control_file) $(process) $(output_sub_folder) $(used_zvtx_folder)"
Queue 1160