Universe        = vanilla
Executable      = run_VandySkimmer.sh
notification    = Never
Output          = /sphenix/user/bkimelman/logs/wEECs/wEEC_run$(runnumber)_$(clusterId).$(process).txt
Error           = /sphenix/user/bkimelman/logs/wEECs/wEEC_run$(runnumber)_$(clusterId).$(process).err
Log             = /tmp/condor_bkimelman_$(clusterId).$(process).log
Initialdir      = /sphenix/u/bkimelman/analysis/wholeEventEECs/macros
Arguments       = $(runnumber) /sphenix/tg/tg01/jets/bkimelman/VandyDSTs_Mar1_2026/
request_memory  = 10000MB
PeriodicHold = (NumJobStarts>=1 && JobStatus == 1)
Queue runnumber from queue_all.list