Universe               = vanilla
Initialdir         = /sphenix/user/ChengWei/sPH_dNdeta/dNdEta_Run2023/macros/run_condor/condor_outputs
Executable             = /sphenix/user/ChengWei/sPH_dNdeta/dNdEta_Run2023/macros/run_condor/run_root_sub_the_file_number.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 4GB
Priority           = 20
job_lease_duration = 3600
nEvents            = NEVENTS
InputfilelistIdx   = INPUTFILELISTIDX
FileName           = FILENAME
skipEvt            = 0
Output                 = /sphenix/user/ChengWei/sPH_dNdeta/dNdEta_Run2023/macros/run_condor/condor_outputs/condor_Nevt_writeHits_INPUTFILELISTIDX.out
Error              = /sphenix/user/ChengWei/sPH_dNdeta/dNdEta_Run2023/macros/run_condor/condor_outputs/condor_Nevt_writeHits_INPUTFILELISTIDX.err
Log                    = /sphenix/user/ChengWei/sPH_dNdeta/dNdEta_Run2023/macros/run_condor/condor_outputs/condor_Nevt_writeHits_INPUTFILELISTIDX.log
Arguments          = "$(nEvents) $(InputfilelistIdx) $(FileName) $(skipEvt)"
Queue 1

